apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:O4w4FoP0Ux8X/dktg5Kurb6lt4PPl7JOzF5QZYusMWRpp5kWvPcIVYpWOzKAaJi1FpjoNJT7kcJ+esmADBJIFPkQvMOaBc+YWyHLPCEdjQ04cbOANsJgEJkKCGI/Fp5/QtAsSK/vTsSLmQb+VXI8gSYKS5kKaSgh0ReAII+PW2L4739BYuMs5A==,iv:oGPIuUqg8FT/X9js31/6r8qk5s3wZIYj1GGaOV3Psns=,tag:Qcg4CqXiw3yvcKZiBxkMHA==,type:str]
kind: Secret
metadata:
    name: ghcr
    namespace: jjforge-prod
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aVJBN0ZFTE5jdURpWXow
            ZnJicnU2dHJTZUxQWDNvcys0VlJpeTVwUnpZCm5Vc01ZQjYyU0ozK01leGJCTG96
            eTA4N3BrNXdOUDhTVEIyenQrWTFDSjAKLS0tIDI0WVVJdUpZTVJmZzZ4QzJTazZK
            eXhFOHBWRVNWM2tkekJjQ3BkaXNiWVkKpCIZRYLQPGnSJDWsWog2oU8sjGfD5yeU
            coyMEKacQ7m27LO/NOcUq8jbpVKNUshm5B3Qc3QANO+lK3xIWsnxiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNTJSazdpeGp3OWFRNUZp
            Y1J6aVRhcnpSY2RZZnQ2QWJEK0VKaTd2RnhrCjl3SkRYOFFaYlhJcWxMUEFBY0VH
            T0NCdHRabGY4bHhQUENYc0pmWDhFZW8KLS0tIEQ0dlh3VHNSRFRxV202TERYTlNk
            SEd0Z2dJcE1xVmE3eks0WlI0bzNlcTQK/IRICvuIgo9xmdFooqL5nSCK5cwYCYW2
            Bd4mDZ4o+p32kJgzi8Lm418zP84Ss71EteZVrauNzepBn0mxIDqGNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:58:06Z"
    mac: ENC[AES256_GCM,data:uZc3/sv/KgATCB2H59ZsjWvsSG3bTDYtf8FDjCgrD9KUOWV5sZxw1cHxV7uqrQctTzHFtQYEKROyY2sGIvypobzMQHlfsKpxcN0bxw+ymDIYzWzvk2BSNUBuW+mn3Jv+8pur8Oc0GCpRkq4intGUDWrqha0SGmnzULSznSGIpeI=,iv:0cth2IDn0nBMj+rD9rXdY604p/BwnqP/D6E4OvtCjQw=,tag:C4/m1E49MVuQlvoE9ccosw==,type:str]
    version: 3.13.3
