apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jjforge-backup-s3
    namespace: jjforge-prod
spec:
    secretTemplates:
        - name: jjforge-backup-s3
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:jW4t2O4YzdijqSuCcMu+C13aAco=,iv:wFY5gXxuyrTs30HCYfmpWzq1M32m0cxudsO4Coov1AA=,tag:Y8XyxzGvBNz4Oo/Bpf14UQ==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:beDetg==,iv:gK4JPjBdZrz/3+SYHtCulPIh/Lkf39RZxY9qkE0eGYk=,tag:unDl7QFHDDQ65MaYGYQCeQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HgnWNcx7dJDIFhkTkt2qelNsihIyuKKRoIy0feiNNvDLEu491QxcTA==,iv:AqcMWxp3r+xrlKwWiYPnHKP+kxlGQm8kOhL2LI3misw=,tag:s6wHZ18LwOTgOwSuRxheUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUVY2Z2dMSXQveUhYbHBX
            WGIvYWFLTEx5YzVnN3FUMUV0SEE3VWhXYVFvCjloYk9hL0taekt4dHJSeTRHbEpW
            SFBxMVQ0UEpaaFdXUHVoQzFOWWh5TVEKLS0tIE1FTkV1dW1CQ3ZvM1E0K1MrY0l0
            aDlkZmN3ZU1XNWRsODJMZHRXVU1xMXcKiWdJ/zJLVm7LHPfy8imWEw8GhW9O4usw
            /OQ/MeGNEZ0g2WKOzWPgQFpHZ+o0FBCbrWwV3sc5bo0T6ZYNIPE5EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNVhoWlVNb2JtT3RYWGNr
            YWgxMThSN1h5bkFKQXdoVitpeFg0QXNjTXdFCm83d1NUSkZXZGRjb0M5aFpvVFgy
            ZVZUSCsyQUhnb1FsMFhoVVVIUnZzUWsKLS0tICtNMWxPeUhEVisrQ0NsOXNzZlk5
            NFBYTHZFRmNhdE5LOVhyaW9Namd1NHcKKxrkLQZe809m3VJsTadFGAjGxAlc7mOJ
            PyfVnbTBR+apMNlhKhF76oXXabcinY294XvuVr882mvl1yRwMj2Udw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbThEanYwZzJlN0tHMUlI
            bm5EM1pmbGExRWIwam91SGpYbDh2QnIyMW1JCjVqRHRxaDBhTEMzR0xmZWJQUnpR
            L2hoWkM1NDFhaElHaXJjbnJiS1JOTzQKLS0tIEkxMUNFeVdVUGJUckFPS3VseENZ
            MFFPUm9pUzE5RkpXQWRmRlMyZmQ5MzgKPgd1Y34t3GMj4EMvBe4Licv/LPtJp27W
            bSX8G3hNHR5InWJODR9+I+Hfg4gJUB1FqZJJZsF47Hc0UUARNYZx8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:06:58Z"
    mac: ENC[AES256_GCM,data:YSSea2+LKRdzSsw4zwCbFHHPO4Hqldc467OcZFmaiDhoHzwlAqSz1U2MHDkxRNPdC5wKiJ9/qsvJEB5M/2JaErFK127Rpiem+HR2/2i2thtpgGGUHoAPr4Uqf50lNI2xQsbsg2g+fHtg2snQx2IvKA2MKuun0PfUNzfagZ3AxL0=,iv:Douz8GhNv/N80npQWtwqzqCPQRox4RatNEBC3nO4R1U=,tag:MtljzBQO+FdM7VNMkkGvaA==,type:str]
    version: 3.13.3
