apiVersion: v1
data:
    password: ENC[AES256_GCM,data:HQvDkoEE/BAImzNmvbtbpZuYpyMNguva1fMZUNlOPzuWYEPyQbMhSlwSwaWU8VtLoKhbiaQAswI=,iv:YOl2WYPKjJ5seMUAaCrv5vLPPUUWakWjpg5wUWZjiuM=,tag:wnyFwKQUYKTIvkDTmTcr+Q==,type:str]
    project: ENC[AES256_GCM,data:7LLGlZdyyuca/woz8dvTOw==,iv:Mv66lii8X2dFcNVW9CgKZVQAyDx/p/dKJ0nOF4/IY9I=,tag:4/oDGpkx/2VHFSuH63MbJg==,type:str]
    type: ENC[AES256_GCM,data:cHZWdA==,iv:SYa8d26LCB22kaInhi4NpHiVCDm3eJyPAU1VhOf84R0=,tag:gfxH/SCBgZPJcJNR0XrZWw==,type:str]
    url: ENC[AES256_GCM,data:u+NEGOQ18Zbq22hGMo/XbmzD95z5lTEJSvoLWZOKlCkBY1RfP7YMLupdNELs5Rx2DawBaMs1nTr/x3bK,iv:vXMJHg0lYqAs/uA3GVvAqXXJfVtg+zCyPi0qXTUno7c=,tag:iBj8C+/gLCW4Uv+athxs/w==,type:str]
    username: ENC[AES256_GCM,data:tQpg+bLPg3vDaW3L,iv:uKHJJSqsYQ2Ovm5wI+29DDjYrr34CAFUGAu//AlbN8c=,tag:YoT9FCctFZXFCK6H2lXZaA==,type:str]
kind: Secret
metadata:
    labels:
        argocd.argoproj.io/secret-type: repository
    name: jjforge-prod-chart
    namespace: argocd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWnFSUG9xUTBjVVRDKzNm
            M2FjMWlML3dhWjh4cjRWMkJFWDduVEtvNmxzCmpjWVF3R2Z0RXhYRVI2WDZ3Vk53
            R2N1SEZpZFR6NmVkQnRQT0pVZEZzWU0KLS0tIDV4Yy9HcnRoNVVkS3EraHNidll4
            SGdNSThncmRqVnV0YUJmUFV2R2d0NWcKmSMOuEy05cV//D9c6fpmLtqxbT1R06Vv
            IvgIfGce4VQdJRfkk9CxLts6EJ0ncQ9v5kY/ANsfmtjAJ5lE8yF1Eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNU1GRjdsTGhOV0lzTTlO
            dW8vaXdjaXVLbFhRdzB0RFQ5ZGhKSzVEWjJBClFiOENmSzBnVVkyOXBVeVVaSDBQ
            RWozZENtZFpnTVBNVzdkTWlYNnJjbjQKLS0tIG85L29JWktDVFlwNkN5S09mVzVF
            S215ZUZrbTFhbmlmU3hLMWpZUGhGQ1EK5Mw8iZWu5ytI9yhZ2So4t1TdKAY/8L2G
            zi1+umqp3aLljKX6MIV8SLERkv3H6l27RKux/eWR8Yq07hXwSHXCJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:58:06Z"
    mac: ENC[AES256_GCM,data:k/PwL/UKGKwKDclldoMR0nzBrIk6FYDoyeZSw8MYaN7ev4gbTJESa2fI3cgpDdmMktUJsDVdtpmw+Ch+V72BSO94owEQBDxRTHX1yf64eTaJk0m3CkSKZDDBYphwRKq4DTKq8vlGMf8CHqFy3w30knT+UdWf3DTcRpGqA3xC5gA=,iv:WR5jgFdaR3tFw0ZdQ92TfEthqmwQeuV+wvP8wdukPzE=,tag:/HJhDQMSvgAMKOQPA+OhLw==,type:str]
    version: 3.13.3
