apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qr01+peVgTOGuSVNM4NK6spBHIIRn2dba9J6Ug==,iv:16knubio9W6ucjor/+X4FVHbk13GEJJuz3ApFqaadlQ=,tag:WiO12y1qTozsmfj251u5gg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:/UCBDnfJxT0=,iv:9ogZZhLNe5pim/Twzo4Ksn/J8P2cZsw7G/ihMRNVQh4=,tag:xgzkRcu9ZWxm8CmI8J2guw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:A7dnhw94YF0klGnf9IyvQeqiHK5lZnlOP0UEYxnHWwvePJ6FDcIMfW5hcICwWlyKW5d6UNY1EdI=,iv:hUQqoC1Yx7lHUMl71U9onEXZaeS8GQ70e7qKPV/jTNc=,tag:q334WokFw+U3sou5xsqFAw==,type:str]
kind: Secret
metadata:
    name: jjforge-backup-s3
    namespace: jjforge-prod
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NEJ3S3BySDRCZC9WUmxo
            NWNFSVNONTE4WnFibVZSK2hxZzNGM0E5KzBRCmFMemNvNHMzRG84RTF2TjVtR3lj
            enZ3bmFBZUFWVVFHeE9nOGc3Vmt3KzAKLS0tIG9xaTF3ZUhxWlBNd1E0TW9SNG1M
            R29ZODZVeEJGc1B4SDFUMTZRSmxiMDQKc/gRGNHjno/d8qOOLHTyQtP3qs1v+R5I
            GmuYuNYbgxDaRoVv4skB06j+VfI93MWe9Z9WLBXCrDVMeonf9iVg9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cXBUSzRWb1Z4Yk5RZklK
            S2lydm1hR290RXlUNUNMWkYxNGF3Y0NyR2hvClZGZ1NDNlE5VVFBY0xESlRaRlFl
            Q2Z3eDNwVkpraVlFekYrTlg3REJBY3cKLS0tIGhFR2hXczdHQ25RZ0g0b0xaNDdx
            amQ1ZTNsZ0VmNzc4QkFVdHhTTUtZWW8KtGurUNOC4FBs19+LeUr7+2PFwDm/kWRS
            4hjjzxB79hdiWtPvsLO72c0PnGUvVyqmdHl6xooGBG5mMhPYqTeiMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:58:12Z"
    mac: ENC[AES256_GCM,data:XXSCZyLGbI13cVbsUwIAuZviCI7TfNwhc03XIONVp5BkEdSa0Aq/OFNjU+sHUf6OJYzKX1yipy3I/DGic28RUYjwBn++MFOYM5evf4e+l/RNMxWFC0w6Z4jI+9RmYfXm3U7D8mLeyVSbgTH2S4sCBCSi0EvMxidy5P93MpGaEvo=,iv:2immiEawi4Jqm3TEbcZogUoJ3jn2MZZ2/NBO91dSLZc=,tag:pPeGSLEMqf/IkP9TnglNSg==,type:str]
    version: 3.13.3
