apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: redpanda-backup-s3
    namespace: jjforge-prod
spec:
    secretTemplates:
        - name: redpanda-backup-s3
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9EfI/mYTsSAV55nx89q2GItFEwU=,iv:l4JYjFZJInAZG1b4GwymExijYJgWcvpiti6Eth7aokk=,tag:YdCzlhRfjbts78iiYIFuwA==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:1oP4GQ==,iv:7hPmBHr64xMfx2A7aRxBn+5mItxd7lcRODyLSG3noRU=,tag:WjwWU3pCP5yWmxL2ebekOQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:h1KDsCqh6EqOkm+c4MVv+MUGQMYWRo7oTvj6Dj6lb6+mehh6JRpOYg==,iv:fwovK3v2wL8RJRPSHTiXiQX8W6aDr+wpYEuJN1yJ+GU=,tag:m0afB4OIOlY5PJSTsJlj/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSjE5ZTdtY29TOFJ3TlhD
            c1FyRTFwT0k4dHpXRWZDZWtyamhEZHBSdWdBCk04RDcvUzFXTmc1cHZyRnMxd0Yw
            aXFObzhNTXFGTEJZS2l4d1hMS0J3QkEKLS0tIGhGMmE1ck9WTkFEaEwrajJuS1BB
            TXM5ZGRIUDJXckZ5bERWcEQ2U3hzelEKbVlBXswlJ5LVsV3kWRJujeDG6ZiZ3PLe
            SGgWslVRL11NT6Z7EWaolSssLdkFNZsjWQ2mU/oXnmmrFumwgdC9mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbnFEejE4eFJpRXlzNWU5
            bHlQZks3Z1Z1am8wUXl2YW1kZ1V5YXNpam00CnFUZjI1eTBSd2RXN213d1BuandC
            bTludDBVSU1HNm92SFhpcjBRQU9FbjQKLS0tIHdWUVVDQmJ2eURPcnErUDV5b1lC
            b2lPUGhmR1RvMEtnRmxCcUVnQTRxZkUKb9XoFuQJNECxA9Qj5f53xbqR/uywsXmM
            uZ8HgWYNy48ZB2s/tAISLDf/ur7De0Jqhl8k4sNt11c4d6T5c/T6Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SzQvMlJlWlF1enhjS2p0
            TWIycW9mNzRRNjZRTmNldm9tQ1pkUFpYV0hnCkM5YUNsWGh2V0xBeHVuS1FwTXli
            cCtRa3dlK3lRQTkvZWN3R3NDdEVnNW8KLS0tIElHUVl2eEJTUFliU1dlSHpmL1p2
            MGJRWnNkcVE2aGY5ZlJzTTZXKzZUV0UKws2Gpg1Fiof/bspceLGwb18T9gzf7eZK
            GXJ5nXmTzgt60OV/fKVPYJowAquRps0h3Sfhieqv6xr/abuum+nBTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:00Z"
    mac: ENC[AES256_GCM,data:DrA6VQOKV2M7sPSVzJu/FZPq1rUrd0mC1IcN7TFse+cpxn9/NlxFyiE3dVhYPAdwq0wfMhPjLrI0ZFu2F4v7w0K+H1Uf9FdtWj4zmpLaDbL1lSiqzDro7NttA87hMakfvN21GH80todxhhpAEYBZvT+mJ5p0yVuPj7KxxvUqsaE=,iv:dDEHYasteW8hkkbNF+m49lYu38lgGyoKA2Y6qrkeWhQ=,tag:LpN70zYcckI8wWxxAcwmTg==,type:str]
    version: 3.13.3
