apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lOYZj5jKn05jUtR76QnVCNh3CjzRTSgSiJBevQ==,iv:RVkRHvM4Z9Hc3wU7FLHlzlWtYX0OxY9gSUN1W4guWb0=,tag:LTdwkzuLJEXzf5OtYf9qOQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:fN1Jg/blUh8=,iv:WDw9DnUxIb4kiJtAWPhj4oUpgoJ3jR1XZY3toO2WgYI=,tag:t8UN+2VqB8eUcztNAVSIhA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:scL8JAbQDqMcJGtgkSL3s1FYiXH1wtaMaYSv6WgOPNUyToCmQp0muXiWYOaEmzB1kLFQwfM/f9Q=,iv:ZEElAYPbffAwkB+TE60VGysO5w42tPQzAhR1h/A0ku0=,tag:kDovTEPRQ4i/9xnQYVYBuA==,type:str]
kind: Secret
metadata:
    name: redpanda-backup-s3
    namespace: jjforge-prod
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RUNXS28rS2VmM3BoVjBv
            SXNQMFg0L04vcEtoODFremRZdWxCclYycGlJCmgwTktFZVhGSnZ4cVRxbVdNcncy
            cDNHSldVL1FXVGFKNjk2ZkNsVWhkZmsKLS0tIEFpN3JFdkVNeHBGa3cyM2xtclRu
            eERCVitYb1pucFRNNFhDK1hsaUpGdVUK5j2VEvSuH6GIMKa1lv3/jTlAeDSsv3Bj
            ugfTm5lE/OlRmi7bnkicZjxIwDQzEEPs9CbqPbPh/Pb8AEhoyT7Erg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaVREYkczWHQ3WXl4dFYz
            Z25DL1l3QithWElnOC85Q2tkeUxLKzExMVJzCmVkVFpCM00wNFRpWENzcWtQYjZm
            eFJpZWsxVFhOZS9HRHJKY1p3Sk53ZWMKLS0tIEdnc0s4Wi9JYksvcm1FenRnd1Na
            UFRhZHNIOWFzQjlMZ1F1aWFGMG9oWG8Kv2q6o+Y94wT+e6xO9JCTTUGJfI1oVUSj
            AcaNtldjEKEQg/29B6SryhYZUP4b09Gbq0OaLcHFk5/qojce+HNbhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T21:20:35Z"
    mac: ENC[AES256_GCM,data:ygnlo1LkNBMHJSmp0k1gcqlUcy/Iok33MlASvBQwGGe4orYBgw5EjF1lAzCTvmzHaUzmP91mxtwxn7LbZ/n6X3AS7Vbci3b7FBwHTmpBHWTOZnnYd3T1gr7uz+xB0v6yngO2W5HA1eB0Z0CSYiF/1nYWnoJS6BdMaThkL/ZOIdw=,iv:qSYcbzedLrfHrrHr58l/1RIXvN0Fk+6z9ZyZyg1gUxM=,tag:K6Z7KOkFcuzG1bPijqLOFQ==,type:str]
    version: 3.13.3
