apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: seaweedfs-backup-s3
    namespace: jjforge-prod
spec:
    secretTemplates:
        - name: seaweedfs-backup-s3
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KFXsU+iALwk0oP2lDFZZoT4t6Js=,iv:Do1auVXSbghMmo2DmU+q0lX2OBgFKu7I17p/ZGA2mO8=,tag:ww0txdKj2acbIfmJWnJGQA==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:Q2/QRg==,iv:Tx9sHUr2ZWnWMrjs3jAFugIk1uzZaeOULjj0Fkv9LSM=,tag:nv7GwcXlqMOw7azzIMau0Q==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bDSc/vMeEn42SKMhODt9aLr2JmPEW63ZUZ+F7GQGvwAON/74NQoF/g==,iv:9O5ULUM93lUb1xXVfs4Gs75T+7MluhBT97eSGM3vf+I=,tag:OWArBnyT+udvKErGf/E6Qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacjVDdU1BV01tVGs1allr
            VE1UOU5ZMktwTm92ZHNEQk9IT3F0NnJ6d0hZCmdmcGZ3S2NUZFA0RklXd012dWV2
            MFNuZC94bE44Rko3N3dZNmJsS1FpZUUKLS0tIGxid3IxeUZnWE1LMTBjYWdvaEJN
            MjIzRUhPODR1SWlqTkQxZFlSdThCZWcKcXYXSU2eMNWsmZeJgluBjQMjY/JJ36Sl
            6A4rmOQacRd5Hei9L20WM+zlkqjhnRI//5U8X4RQ1gC68qG7yrHV4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY0Z3anlkLzZ5V1ZMWlV3
            YVRuMWh3VXVKcGJQTUFuS1VteXZNK014WmdFCm4vTzNic3FrbWJIZlI0ajlxTm11
            cTVPNWo4d2E2K2J0Z1RpOTlVWkx2RzgKLS0tIHBtcTkrS0dPV1Urcnc3ZkFyTkpw
            TTFMZXIxRVpxZ1R3ZEdlNlNCQktQblkKQt5SygXp8FxOFJrODDwYlCQTFqArsLy0
            zcRdtdMsvyYpddfetjvFE+HTXO+vHpUVqLX4hRQqXJ7mNTY5BZvoyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUHV6SWpxYy93TzU2TVB0
            UU5CYklaQlhSRGRIcGd4WTZNTGpKaWdmaVJRCmUyK2tEZ3J0UFlzUUlCU3BMSFJx
            bW1Ea2FNcXcwc0xxMWN2enVpOVJQOGsKLS0tIEs2WS9EVjJpZTVBZ3RocDQrblRW
            L1NaWjhoNmFQajVhaWl3cDAxY0lqLzgKDkyTLR9nJwHMQxEEpYUDElf0VSOOZwSR
            8tqUIrXAhw3hBjnTE81vXvBqY1fy8NItfNbcy7Y7YTGdGTAyovimzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:02Z"
    mac: ENC[AES256_GCM,data:BMYvYjlD0+6O+MzO9e5hzzJrRwOw5VdAJ6FfCxVHdJnQXLQ4/zbPIKGFeNnkEbd4Qfx2IvuNTddpS3S5ETHoQtlsQjy53/QSy4qj8iYJdn9N38NCbPcgp5Ak2QHIXb0+eAqWG5GJkE1OBv+KNZrNIyz0CAoW//7WRdsRB1+LD/Q=,iv:fHREsEaatiaQB4oBNF+m9i3gXW+exihsEoYnt/Iqsj0=,tag:8djF6ECxtXI5IDVzyGSh6g==,type:str]
    version: 3.13.3
