apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rcs8c/tovUKIAIPAtyIOHlEsUBdpss/XLQqnEg==,iv:yn+9K2bDk+8eGuupgOdBW20skdiDSFgpJyZcY4lHGt4=,tag:y5t6Agh8DD4QDhzBWWlQ2w==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:ZSgCx/osKNY=,iv:GBehn18t/pIUSuQbVphdRh5stExhSJoqB1tMsdCmBOs=,tag:2weJJDW772tbjKs14x1UZA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0+Sphq6h28RxFoZCxqh5jrnyNyX1Rwlrf2gnzQsO2KxncXfgquAxyaHphRFkNcM/O0BWT7cYidY=,iv:kCMp48/9ggXw01J9wJ7e8F6XsDgxX+xcg2TP8StJ5iM=,tag:oR1XsPVud/qxLWZx1AvULg==,type:str]
kind: Secret
metadata:
    name: seaweedfs-backup-s3
    namespace: jjforge-prod
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeDlZeXllV1dQb0tZa0h2
            SE8zMTlUM1VpZmFBTnhTQ2tEaG9MT3JQWkdnCnJyajYrVlUxY2t5UURkeHlrY0lX
            Zk1TKy84d0xMVTE2L1BiUldlcHdrZUkKLS0tIDRPdnJPSWxQb2E4ZU9qMGNmWlcy
            Zi83ZzJOTWg2RGozWkR5RDBhNmZha28K8m+oE3LssyGlxSsIyWagsFqR55fMehE9
            CuL4EG4DYY55cI3YxZ5Em4UvV9xRcdQzCI+53AM+NMZgc/4710kIGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOFVFc0hmWEp4K0g0MFY2
            aXVHU1lPV1YxbjV6ZmVrZmZRanpNaFQrM3pvCnAzM3JKOG9GWHRtY21xSmFQZzJ1
            OVkwZ2VUNzdWeHNyYk1PTVQ4N01LOWsKLS0tIDlyK2RqM05hdThoWWgrbXhXWWNx
            bFpBd0lzWlZHcG9XK2pRbGRxeElkVjgKbp60gmEXrmLtn/icep8Kf+KSp3I1joNL
            hmDI7T6nvRDeNgoS4jXiw6IkwXsz4rEp3z6RNcGSonlHQ2IO8PGrcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T21:20:37Z"
    mac: ENC[AES256_GCM,data:xkPPCLoD+KIaqa8M5pBBrxCtUKYQsOM2cZpiWgn2fE2m3lu23502GPRLEMbrkgJtsfOyGRDKGRNTjJQyJB6FxHjJqlUvxsZzg5Qb7plfotzOw+AOb8+0aNDxWNYgR7MUZJ10HfnpVoKKOsZuVHplEVmNhj/msQpZfCD29jIZGY0=,iv:elZfz8GVFsrPlr8FwU2T8gHRdLtK+fd7tZrnHMYRQ+4=,tag:6rr5TPbEbgmMJoPHk9X9VA==,type:str]
    version: 3.13.3
