apiVersion: v1
data:
    seaweedfs_s3_config: ENC[AES256_GCM,data:g5UQGuiFEW0XEVEtqi+L+Rt9TqfK0YRrKSbHkxKKjHzYT7kjAkA8Y5h8oeuETPEWgzwW9t6UPQ2sUchxj+ANvSYHGq8wayauic3a4pabfJeS0uoXL93OXMI9YUdJeC8ZcmB0y645s6KYs2qPQ5ujLVx7LytFzUhLoLD82THLt2wH/zGxOP+SOBk3LtF0V/W/GTHllUpRSigxW6yYbmu3xScQh1KAOZv+mjw+28qTQUv5SxZGQ5W7kflUWqw59eb4yf/JLXWt1VcWFo70RSxvkLzV1/048hKZriy7qjL9jzzsvff08sDg0oaRRkk8cih13TRGFTRGuTxjkKrV4nKFlgQI2ga+WIAFOxqs96SDXz0=,iv:c8+AlxtnHgc9ufBJmM6jO1NSFFSHBjk60grDitZ4/y8=,tag:De8HbIDSq1DadJbxjUR9CA==,type:str]
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: jjforge-prod
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveTIvZDUwVHk1eVpscW5I
            dC8wSFc5S3FhOHVQQTVnbmo1NFlYa0pHdXh3CldrbkVCcStlUHY5ZEpTcUo1R1E4
            VHZFMy9abk9URmNhMnlLMDZNQlMzM2MKLS0tIGhrOUZPbkNoMWduTWt0N2dQakNK
            RE1lK241cVowZ0RwVnphRWNJakcrK0EKXtNnPEipabSrcs6EN1wZYSVRHntdT2U9
            TBncFjVWTIf2RN5Jl1PezbMVdWxcOvBsEUnLtH0rhz1rM/13EmCtag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbnVuOXhSb09DejI1Um5r
            MjMzVlZ6Y2l5bXIwWWxNbHZnazUxUGIxTkQ4CkRRNWtLUmIrZktNUEFDd0UwSDV5
            MGtJd2NzM0JGeG93UVo5TWpHZ3IvYXcKLS0tIEFlK0t2UjdhOHNCcUhBS2hyUmZk
            UEZPOHhzN2NNRWxnY1VNM09UVndwMk0K3h7OvgDUyu81P0DJf+XnB8lQ1/kZjC5+
            SP6VFnS92I5u4dpiMXkjeXgzpU7MxW01xJ7m9AeWhfGu5qCt6fYmdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T21:20:38Z"
    mac: ENC[AES256_GCM,data:msl2wJ0XuTXF2T1nHJVnIjYYsyIeLXAgHBIVOokgzR0CSklAdEla0lP2RRaZI4pufSU6R49w10G0j6F2etz/JIVq38W0cQn9zXuD2BpsLALRPtJ7jcN4V9J/z6QM2Dpw4i/Yg7c+wJwXW3q1eE76KVmrV8SBJ4YlwRt0rG3bnzA=,iv:v9j4vkuzrlJn3dSx+z0SeZdYK2xaflGtlfkcxkUQOIA=,tag:2FSsDsGe46x4yREgjRfrFQ==,type:str]
    version: 3.13.3
