apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ncaleague-backup-s3
    namespace: ncaleague-prod
spec:
    secretTemplates:
        - name: ncaleague-backup-s3
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SDuSJtEPh501MLx/e8Fd8wN1Das=,iv:e8nF7DoY/oMrjNyAQSyqAsMKqbIVdLBVvJoI1AuCFVw=,tag:/kYBMXnhSCcWouTXZCe9dg==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:j4kLOw==,iv:rDfsUySoEfigA58rzFLOMUE0xo4fiSpqW4EOjKr0Op8=,tag:lC7fH5LXIlGz2vQzUzYBVg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GyaDDmDuSC0kfUO4Wll4h5d2dvRZohoFIPskTqCW83KISj6jzTMjEQ==,iv:UL+uaHD+WUiTqf32ANk0gj8dLW6tWu41BGN4gZpHKUs=,tag:dpe5AnSh8W2U4p7bKt1b9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSVJrd2xTYXk1eDEwSUlH
            QjhCRVBCZXY3bTljVHgxdlZRR1ZqanhvcjBjCkJ5VkkvZzgvamZQQkVSdmVCdXVH
            ZmN1cW1JbVc2ZnpnQzU3VXJRUlNwWEUKLS0tIFMrU3NiY0o1OVRQWWVWelR1SUww
            WkNRV3BvbTZjK3ExRG9lMzRzWFQzY0EK4txn5ExzYgFBdtJFsKipzOqKJm4FwUKn
            trvwgQ9Bt7m6mX2tNJA+sXBFn0Np7uuLbUXB9VIoamsCoVvOu5t+Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRVpkdkNZalBpTDgxb2Q5
            RmJXaWEySGRlS1RiS09rdzZkdE5DYkY2MVNjCktqd1M2M1JERkh1VW5Pd1BhRi94
            SXFQdDdldHZHOGJhR3c4azU4cWpEUkkKLS0tIHlTUXZ4aXhpbTgvdU9RTG9VSlM1
            WElXUjZqdEJrSGsweStia3h2ei8xNGcKRL9OisHnF2E71ay9Tl/vMWFmTCnUxShp
            vbZNyUE9Hv3ZymGqbUSFwEZKmklAiIcN33y3M84v7ZJaF/LnoufAbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bFozYXZGcXAzZzRjM0RB
            b2pacTJFTFBhVC9wYndmQlRSSFhqekJjL21nCktzMVFZQzFsVGVsM2p1R0Q4MC9l
            LzF4QjVteVFvTGJjNEE0Njk2NXozRzgKLS0tIDhqSWRsSjh4RzhsS0M0YVNpbDho
            eTFKUVlQSHVjYXRMS0l3T0U3R0hxQUUKWKogcDX6XRpVUWe602mDKLVp32FEJx8I
            4R2GcoD6BNvLLqri3Zky9q2TXdzt8PiUVWD16Ft1nRQsdmPrjtSiCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:06Z"
    mac: ENC[AES256_GCM,data:+OCUvJNyylDxHICRgTihYIxklq/PUqqn/Us7fSKjiSxgZkYQzjr1GkLCPA/znFjT/z2ZZIWZTmKZ5qA7X0wjAIze9fhTAR/R15DSBy2d0QAfZibqj12RSGkfvLOSk8RutHYg650sfSfjH0eZODqBOFMYU5X9k2NgaG7qSYWANnM=,iv:CX/Cz2Ndw3ufvcOMI2FilEkKSr/0O5Ww8CDIbIRiQ5s=,tag:Nll2KaB5tJFcgPwPu0r+0Q==,type:str]
    version: 3.13.3
