apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:n6K5p2HAX7bozZBpUV1XvdExPxgq7K4FQnzWfg==,iv:pCBccPxkhCuyCb3KyL7zs5Ut9lIByAbg5A5dnY4OGJg=,tag:L92xX5dU91+8sDf3zUG4nA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:zrG4mYyMRho=,iv:zznVgp1JwwWNvNkucwhT6Yqf97R6OXd74Tygpgk7zBw=,tag:1/eRUUOuK8Q1f7p0tuS+AA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ux3wRm78n4VBmNsiETt0dlmjs3oD1/igKIk3u2NlDiBrBYP94n46o6X/NmLSTEsw4w3preU93QY=,iv:U+t+FIkiT3jwogNvoSsENowxD0LreBG+l5yr5vqTVAQ=,tag:RM2T3L60QzwDSL/sOFIlHA==,type:str]
kind: Secret
metadata:
    name: ncaleague-backup-s3
    namespace: ncaleague-prod
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRHlWVWk2S01zUWNZQXNl
            cy9CeW5aeXdKU3QwS094S1FrN1djYWNuTWdzClZPNHgvYURoYUp1RW9EQktFWVF3
            NDVqZU9Wdlk4ZXBqRHJyRkZSWUMybzgKLS0tIHpTQkEwL1dvdUhXbXovYzF2TldV
            cVBXWmpHUFlPbmlUOEFVdXQ1d1YvekkKBNPUdrHhvyi6C7xCQQVo4Jux7jOnyhPo
            TOakUX/U4gDAbZmi9+N8RkGjKxdlRuR0KThfkvLpbO/huKEi8wZDPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbTZMdUpBWXhNVlNXYWxt
            Z2dJNjFZWEt2QmZFOUx0bWxXS2NSR0o2UVhZCnVJQVIwbnJUOTJJRDJQMGd0Mnhk
            MUxXVFBDMkVPcXJxb1lwcU1DM08wbzQKLS0tIGJDbDZ2UW52ampyM2FsNTdjamJw
            S0poc013T1ZSTUdkTngxekY4dVk1Mm8Kj6Hqf857eghr5ioZPouvSa4+peFribgf
            OKewspxj8hmW9i3jWdYtT3cjXr6ouR8/SCQk+Qlw83SUKSZCTo6kqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T13:22:55Z"
    mac: ENC[AES256_GCM,data:8yqsa9E1BKiP+Wyw60D9pBjlVVgoyAwFWJZ6CpQOp88X1Hda6rNW1B3B4+jfUfaAd5v3VvwzJ6SeiA5h5y20a9eW998MRmWG0t2zhamOTFD0a1r4bYXQIf4ls4wv90BcAMQ1wWCyZ5B9FkiaSILeW3bR143hE+ckzFhL5djJ6fE=,iv:07yBJPXfDUTAONm8odvm8nL4S6A3W65hKD4KzWGGZbM=,tag:5vFhtaddzqdFV+Wci6tv7g==,type:str]
    version: 3.13.3
