apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lR2F9fFHvZzbFZ1muiB6BRw/ByVzhQfaimoO+g==,iv:CSKDg4gU1DYCLrclmLEKTY7mUpDnxny1KIBrxgSLZjY=,tag:dNrlnaHoz4AXGkbtVITyLQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:kyzCnKOeAp4=,iv:BvATqKB/u0x0kuDgUxbYE6ZZgayaNS3yPSrfWJnRYRQ=,tag:dcqrSqoMaqxZAXPUSGHTxQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bPrhw5lZ1pRZPCrZDy7HrOUBNCfIR4d5HUZRfWQRAW8IY+Grv+yAnFNHiWhxujA2L5GB70Irhdu3CkMJXofGkGbhHH78UuAMmERAscqQnSbO4UG1JTsWsTKY5ijCGQrZtTWVCAm8W7rhCDie,iv:GSgof2KQE9BKJAc2qDfs+UtvLdxFVg6/yIstWirWgtI=,tag:50ijbbmYJ4mRLMF3xpiKEA==,type:str]
kind: Secret
metadata:
    name: ncaleague-backup-s3
    namespace: ncaleague-prod
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a3k0bDc2WVpsZGlPZkFq
            YzkvYkZaTGQ2UExQU2xpRmxPcjlldm1pQ2tJCldDZ1hLb3RMYmY2b3Y4ZE5TcHd6
            UTdBOWtjSkRET0lMcVRicU9wdk1BRWMKLS0tIEZNeHN5SmVmbDA0THZnUEJUbE1p
            djc4MTRUZmIyL1dLUzFRK0RMRk1RbUUKGg5dunZdEnIxzWJ9D+t1YXcR+XoPn4Hf
            OrKv/dXmkypInw/0BdxiklnOYZz1Vp/On4BfV3db+In491A90oWhww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU2VsS2tnUjY2aVdnY2RP
            ajZ4UEdQQmwxazBSbi9ycDBLMUNJSE5pQ2hjCk0zVllFM0RrWjdPdjdTRmtmampr
            SnczeDAvY3RQMHpqc3d0UmZmRlVzUlkKLS0tIFFBcTRad1J5RlRwSXFVSnJzWWN1
            OS9MRDZtMUVqUUYwYllyNlhIUENOV1kKfUqs7WwUwyY4cIuQUt9l1XdvVJ+QjMMg
            fa6FQ1/CiGA0M4+2xWixfbLdxZx8bBjnmBKc7nYDNc9dQph/MYfh9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T13:04:15Z"
    mac: ENC[AES256_GCM,data:H6eMSOl0pPv7gfJDxYrlHGfyQgJEY5QWsXch/Ng3PNUe/Nkea3yTceREh0c2+wvwcNPFZto5hcJ1p6s9+vif/6kfq0/hKplxCTuUlvDrdJw541pPiwaYrn96mOKkFCxL+3sf40meGM34c8Fc8qbFGpq06yAx7w8AnWoEe2OT/wk=,iv:0r2XfKOFXoEZurk1DDAhNdbXAZPC6loMxo8F+hkRtuk=,tag:RoSqBXAsTIUJhSeuH+tb7w==,type:str]
    version: 3.13.3
