apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-notifications-secret
    namespace: argocd
spec:
    secretTemplates:
        - name: argocd-notifications-secret
          stringData:
            github-appID: ENC[AES256_GCM,data:myldC6JCIg==,iv:3JTebTL89CfWg4jMcDO3tCLxIcsWZzvgolkMWUvPpek=,tag:PNWpaT0mQ211XqXoOGQmuQ==,type:str]
            github-installationID: ENC[AES256_GCM,data:YUBqJMn83Fjq,iv:HDmvtW+gDoYSkIgs4L8/Xb0YfmTANmdYaWhdoDf6gE8=,tag:xe7RAPv5mVi+3iQnzGqm5A==,type:str]
            github-privateKey: ENC[AES256_GCM,data:d2bo0mkiyEZL6oXlOHtuDGDcZ+5zUXgh/XcKy41qeXkyvEvBLROoBl73zyaYBvDdi7CENWxc08ewTCKCogGmWgO9h36C8TJvCgnYxycrrsWFABsuuVQQos/9HcqUhZo16AXScxzzQDBurx+UA4FHVojH+5Zh3+2uBlqMjKJOP3D7qQ2HilfOlN0AGX7JWf/4V6Pc/O4qNJPA8vrz3xlfNYAJzLIhnHyNkMZHLxbYafGChzMyOwxFGET9Y6BNZyzUGxFv0Z73uXVeISJxTJygDhXXTpst+UAHPBKSmQqyd8lS1KR15N+yJ442ih/vb3pK8JhVzTKo/Q/kV8RnKL4+dB3CEgSHcwHzdhD9nZdnb4xdVu7qDZ6YRJ439E+6vvoc/czda6MNz4dLpwmdIO8pjyC+5X84I4OrO+szcna654bLeIg276IClG47ewcZVFzs/LES8htrS5vbRRgwVaEr0RrqEU17nccorZjz2+z68Ti+eMsdVJ9YArE3CrOrqV9gJ4xh4xv11vRbLRbSNi0mANgp5WxU/tkN/H4m35uuQVseYI47xwHah4KRQai5137gJ4YMJOPgNKJuYzb1AFHD+9gKAdKLB9l1wtrcStKJn1Gj4HkCJ7IGMEvYUl9caxZ2n3E8/GLaTFnA79qP4uCoiNmZBpesBIta5Fr6AGB7pwoWll5x6NDXyvFIHwTQ1tTZlDwAH2kh23fEyUA45tWKGjv8ea9JvSULMZ/EWe4mQ77XDs4QCn+ERqjH97o3knVyYxzBg12j4a2EIJn7MqSLbGiDm5xJO1zb9ROr5fk2hQKNx3lJCDq9o56BuUBxbWMmxCuELYZpa5R8n4g/zaZUb1oCSFrfx8kuAsF1IF49sUOiF75yoV8BFrI2RETRpfBHCIKB6vxJRju4pziOi0cGq2xGbT2Bw5NaU3T6X161yNx98DxpdFPH2+O+dxkyaO6tX0BsDmqc0BBG+Six0KX+1z018SAZsfR8jXs/ucPFgyPQy6/HZIrp7pUqzG9s5XQBpoB6iqb9V8xz2tMjd5WDBUQ4dqwy6LMUdV3+fs4PElknhzCyfNl/LxWQNknRXkvVRsNtn+lrREUk9T1F+rJZ0/vnrZvWmhwQywrYrnZiYLtP4axWkGdS9rR5MIg+zCPt1hZZ1G2OYFex6aNzPouXaEbYFY9Q5PCTXosHUaOU1d0myr75pizhgbZFDmkwKCCsZcqnLswDuvqRZdFCPgGUY1wsUVLVasP/6/iIcsHwn2i+H9oJvR8+/wttvF+lOrEbrGJzdJHSUVInNCfQKanfvlttNKjr9tOlIHXtqQnRxmuYL6YoAfHkGbvf7WnKk1bNWt9SLiWIL56RVNqYCnzcmKy6TRAWDz1ChVZ/zJgHAzEiSHC+HIf13lAtj2rvs+N1TcQCA4hKhuos9vWR+VuBFk3K6ZWI/8SNNu/rGaC7OosLG0LRaquEQ7rRm0qtTJM60soeG53BqwbWyv//n5+KImmuZ+f2I6ku9vy6KtXqBRPkaOuQkjLzobdI2Yg3JpNHgB9+skjX3Zh2ydrQpjUMJg3r3RCgcdRAxCoPCbktuf1TeYoujW+fkhKij6p8xPn3hk4+a3sX84Fi/nO+lY8Dx1qQUSchqCJCQMVw2NnwPKa//l81xynmsBgkTVQmdpysNSvmN0sLFMzR6IeKywjkuSM6C/g0rE31CkkxWU6TNsWdQjm3Qwm+6D9C+m9Wt/73FwO08Y0Xcy8u8ZBYGjQ4CG38s6FwB1yXaBtuix9DkEqWE9j4m+hsP9pk9AKrI5tqmcefIlphywXxSEmBIwcBnCmfYAXy6R8QDhNmHjMhCQZ3HweaXuoRKCCl7IOsJplszW2kY/zSF5uvq8gyPgHzaR4MZwEhIeBm3hy15bwCya5iM/irHS0SQsDxK7pYtexH5QlTEWat5P0Aow1UUfQTCI8E+sWM74oJCgTmaZ5ZCb6+01pbg3P+UL3T40b+CX9DI0lw4gQhvlPT6H5KzT+WrX/zaz1cYihQ44iLnnSuvwqeFh+Jkk3m7de5JJwGwdRUuKm7qq7uOLkpVUUKqex8ZlbOB/PuHAIFvnDIaLV9geTK/NPPiJFOzJqpVPmyKYZjS1ol+Qu6zZ749VQqRmoHcOl98Y6UPF93rIXzCvP29ovH2UfiXGRVpdhFb1wcZ1ssEgsWNgtaVhRVt1iUZBfhE1jk4OyR+G+QYOpmhJT8tLfvlEWc4LTLSJukDQ==,iv:WJiERD0KyLNYPT1vdbxTpwYZZxi1tUQfUX2dOcXQfcs=,tag:fpMherdPox8gTKfsTwwKjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMEpKVXByM2RKSmNzYkx3
            QmhSMlFDNUhjMnJjYTZWSmhzTHREclluWW5nCjVmOHd0YnljY1JLdzhIYnJxaGJX
            WnB4K1RQR2FveDdKUXBpRHhjWlMyQjAKLS0tIGdTbkpHY0orVGFxNDNZaG1mN3pv
            WWxpZ05ybVcrbHFjbXZBS3FZY2RTd0kKWWgw4tK+j7w6RYCwrzJ2kcZM1Dhlv2Z4
            LerOOm2DJgtZfwWHHjK82/iFflkDSVVdadzr8UV5K9wZKtuLvT4ltA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYzQ1TFVlak43UFVFdE1U
            am5SalNMTjFpTlZsMDhmVHIraFNvclFSTVhjCm5paW9aWk5zNzhuUmpNbEN3WEtL
            QjBMTDhEcytvM0FMMDAyZUVUdmNUcFEKLS0tIGoxdnVZNUg4bmFsVUZCQW5jamsr
            anpnc0x0Q0dyakM4VUNWd0NOVkpIVnMK7600ieNQPXNo7mW2ih9OswMNp7wdcZKf
            iL3YVKxwngnZ4tvXOqj9HqUUbLWL+2dFF+nab13FwOp37j2s2nxvaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNktFdlQyUjRKMG9GQy9J
            UmluekFlb2VDMnlOYjZyVGlSSWJ2aXJ3MkM4CkZYSm9zMEp0VlNsU2Vid29jeVBU
            NTNTQVEvUjJZK2Z6YVo3ZEsyU1ZPancKLS0tIHl3RWF3OFhFbG1JSHMybkpENVg0
            SU1DbjFDMGgwLzVYK28vOVNjVUdpNVUKSvsMRwFabcza3hiFNhI0xZKwd8d1CSrN
            zMTtMh6blshppHYy778YJiETzn3nAH5r6JRvr1E43L17pAb+HXfGcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:10Z"
    mac: ENC[AES256_GCM,data:tRKpoCy8YIl1Y+qPhSPYE4cFsz3gEZdV4mocykJYuOhH3oW/TUw3NsZvmWUJVmseZhnQGNsu2o4ndUo4Ux09j7Jkb6uItZXtmdfqcgujfAlBms0IHeMW2+YpCqHnr/xB81nDySNh/p3dLRH77Z7dBOryTbcH9B8/XzLpgl6Snn4=,iv:2vVGh3Gc8FDb8NcRmtLh8TxjdFiyJx2jQrOuTkjR09g=,tag:P+usYIoFYiA/Wx5iR2UW2w==,type:str]
    version: 3.13.3
