apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-github
    namespace: argocd
spec:
    secretTemplates:
        - name: argocd-github
          labels:
            app.kubernetes.io/part-of: argocd
          stringData:
            clientID: ENC[AES256_GCM,data:n9kRd4rYdOyigT3xE3kK/8CueeQ=,iv:JR3DqTPkBYc15Z3uIDspqVLgJhgq02G7ofKtZTqB5SM=,tag:Ht6hc+y07dwhObSov1iYNg==,type:str]
            clientSecret: ENC[AES256_GCM,data:kj3m7Ux1o2ruTQuDkFl9U1L9SnUuLXLxylv8yrmImOBer+w3hHeDYw==,iv:5ldAiGx/4NtBxHE82WTjcZ2SENQucfUpz0r9mNYT+B4=,tag:AOiCCoqtCtr1JneRjFCu9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNkVRZkZudkNzZDdwL0py
            Mk56WUMrb2tSeVhHb1lGQWN0T2tzQkxJY0VnCnFNeThvYnh1elIrQVpROE9ZMXFx
            OWJFd0VtNHFFWlFiQnpLc2E3WUgxOEEKLS0tIDMwRFN6ejVEeTNsMGRLd3ptWVVJ
            eFVWVWl4Z3B4VlRKMXp3TmxGTkxKWncKle9JAgQVXcAXOTCRuL7xO+wwdXtFNO6X
            mco/60J1Z4Z6AWNCnqjBFq2cTmYzwvbh7Yiy5nS89oX+xxroQmuUHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNXJmd2dJakFHdUQyUTY4
            TzJudjdETEJJVHNrWHIxRXBhby9yeVZTcnlZClpUUFNDTHBqbWRqOVhWNHFBN0xS
            aGpjaWo5UjBNS2RVREtjaE9KMldQRU0KLS0tIGQ0WmYrU0NMOW5YZm96dEhVY1ZE
            L3hSRjNKa0lmb1lRMXJUMExLeGlvWEUKSaJJ3eDeUstS9OFv838f0tWFaaRI+qJO
            t3l0z9tcZWWMge/rPYnG44G6XsYlA+x3B+FcCd5Bkcr6ISo0GrdIHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveGtGY0JLSnVEb2RVY3Rk
            M0NsVFp0bE40SEh5QmJhcGtOa2REamNnWFI4ClFCcDNaNjZRb1UzRmpVQm9tTXk4
            ZVlsRmlWUnJ5RCtkZFBQUTZIWURhS0UKLS0tIFBDK0N6bFNFcTlveUxTc3o5bTM1
            UFJaYnlkRDM0am1NWEk1NWRQQVpnQmsKZbHqDg3CujkpIZiwaznT8Kb2uGeB8Wxe
            sC44DSkkZJkynEdFqM7Tl3X30DVjkAmFnXSqjSR1sBTaioJFThIQ6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:08Z"
    mac: ENC[AES256_GCM,data:39KbsaDtAVMo6bW6Y7dktzGUbD0S1N0sx5p9A1+R7MrRSwwP9o4bsiNW9R0b43A+Fbeg1vKdl5RUIH6CsrSIqkmUUIPvhPLvjXElzVAFgqChQDc17axoYDwxGKt34wEh30IlCBICtmNH0RKByGrZrUM2DXRtd9U9VLjgU4VWmB8=,iv:jXDyGhmtK+L1lgkEQ3lMsZ2kxcMYb0huWRMizRLfjtk=,tag:DEtDAZu6Gvk4FQQ18GFtcw==,type:str]
    version: 3.13.3
