apiVersion: v1
data:
    clientID: ENC[AES256_GCM,data:70Ks43nTLFgxDw3mZoCn+6O23hesM+nt6LjESw==,iv:DP+C9jOIU6X9U40CpJkHG3HWadX8G2KAGAtcr27Mok0=,tag:+WVfo32kJ6dn9e2pa9lVow==,type:str]
    clientSecret: ENC[AES256_GCM,data:0lXdcvaVP2OquVG3LiPNgcqQYSa3e3VhqNSICtaL8T+jsqkTNl7LuXXBxJJa3RohnpM7ygR+hZk=,iv:fOZL/NJrDM6AK2KBWpKRkNacKOdy2K/4Sj2r3oMGpkE=,tag:Wiata9he3d+kIdD8i0s1JQ==,type:str]
kind: Secret
metadata:
    labels:
        app.kubernetes.io/part-of: argocd
    name: argocd-github
    namespace: argocd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYWg3U2cxU3dwUm1LbUQ2
            NXRsTDZGRVUxQk1oZ1FVU3dHeldXMC9IZkdrCnN3bjBySHN1R3diWERFM2dKdDY2
            Y3U4T2UyZndsYm82bDNXWWo5RHVGYzgKLS0tIE9MNkZlaUkwVlRoWDFZOE9XL294
            R0dQWGd4cFBHU0lQYU5jY3ZWV0l2TmcKvKO0yJ999e2M9P8zvHKuNiQoLrnqv4d8
            cwuPnqySutH7XvSrZQdAbxh8n9gyy5gW4rphR8EhpUiSviqiBSFcbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdkhveExndE9DbTJRd1dM
            blg5c3duNjdJYjhJVlFCNDA2dnFCSVFzakQ0CnoyOEZiSVRNSk4wS01MRnhpNE9U
            cGNVMnlvbEc3dnJDMWl4TjhYR053bFEKLS0tIFNHQmJVK2NmcVRPaEptRk8vVm5I
            elU0dFZIeUFQQjVkb09PcjkvSGFBVTQKaSk0unCxhy3zJrq4dLQY5MWNwbHwtimn
            GakdLzxFriMz6CRhFbUzGivHYyOhfUwf6p8eJcoZaG8OI7X++/roAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T16:17:20Z"
    mac: ENC[AES256_GCM,data:J7hlrM63nBpy2CssScrtrq3Qq1HuhybrKbm0/d3UDVD3M023RfLFFCCPs15ZReVFUaCQp5G6YZMBN9KqvCpTOjRHV57FmVCYV0pXRCGeqkgyAVDb/0xgHipOZ437ZcJeNC5o0UhjpN9SLI5aS2fNfLAQFB/X0zR6z9ShP3o29hE=,iv:CwjENCJaUiU0xA0pkHU0d6eHISXDujDSDsxJ8QuzjGg=,tag:08O2oH9K2zZFgNvRV5dgNg==,type:str]
    version: 3.13.3
