apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-alerts
    namespace: observability
spec:
    secretTemplates:
        - name: github-alerts
          stringData:
            token: ENC[AES256_GCM,data:mPCTs/6tkfj+wVGBnkvTotoISysXOUFfF7+yqmk19Xmslz2VvPZoOk6GDayD6OUwhVTMfpO9ZtPvGASWE3Azr7IuMnnZN0QBRJ6iZ46R+mh2UaWOE8i+N3b1S560,iv:nndRFU5ruU8nFPdyGUZnMdRjEPS5ltZQrhLxsevr4K8=,tag:ar+dzpfGYLfwhiRFw/UEYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdVp1MWsyK3ViVEpUak90
            OVczYWVVNmxYL0xRV1ZsVXFMYW9pajVjaWhZCk02RnBScmtOakVoQTNNMSt4VVd4
            THBvTzVRVnUzWk41MWtEYUFZWloxeEUKLS0tIFBRVlZrNmE0NmhuQzJURzRGUUJH
            SkpTMUdsNWdnVU1YejkweFpBL2ZaZjQKmGNnpk6iUREr+7W8fufzOa1XWG/ExIOq
            ZuN8ZcXs177MT/dct7wYpMHFQwFymhRQqkbY5TSWf4/PXxKupMcrWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NmFyMEk0cEp3OFBqYTVN
            ZDJIMVFCbDB0ZG82cjBBczV4c05lMklqaVVZCjdsS2NoZkoxcVRVQVgvQTA4M0lU
            QmNCVnNTZ1pxWUpQd0JWRXFVQk5lWVEKLS0tIDZOeGErcUY0bXNwS3hCTjYzM0Zk
            eURBbiswdjJ1TU9FaXNZVzFXWXlCdTAKN+fXfw2J4oV3aVa2rduKE64mHK3XNrfA
            /1VF4iqG/R96Iz6s7PvRPuGj1SMji52XJUtqGXtB5ZaSURiUcZ+QfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2THUyNUlRSXB4am03ZFlq
            bHNWQ0lxNnVzTGplQzNGeXFNbDlTTlBuaER3CkQzQzV5QzU3T3M5Qjl6MzA4T25Z
            RkNMSWNLNmdiVm9ZbitsbVkxbWN3bUkKLS0tIHIvOFFMaDF0UVJGczQ1TDUwSGlY
            R0tSTTQ5aVVCRENDQmxDUkpWU0VOakkKXK8zXW53MIPXqp230SEhV1HMjgpV++1j
            VjklcptnvbfZnY3p8EFNDEN0tArUT4e4xTL4Dm09leWfpH9cNE+GDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:12Z"
    mac: ENC[AES256_GCM,data:DvzPIK1Tv6buJLp1CK+KRvQ/Nos0/UOTY5ukjebl0aSt614duiGgx6faNLW0JX556KWtfp0OAtA+kTFkkhUEXVWIuNDecVesEMkc81nCl6tFnWk3HRGD4vvOFaqZt0+RKPKR4FDuWxTYEjN4h3rvz/6iLbF/vZHFzBzTgSj5jcE=,iv:TQyyimZnT3xgFe5wrEaiM94LLCAMoU63dngb4zsYSIU=,tag:07qaEv7ckU2rvjnW1/To+Q==,type:str]
    version: 3.13.3
