apiVersion: v1
data:
    token: ENC[AES256_GCM,data:XD8NFMWqj4OPxdVr+/11V94q3lhasYxPg0LFgu50k0nO5RM1zBG4YT5G0zpO0z/CDn6uOz+G2pGWOB0t0fCIVjHM9KW/h9TTx2OVxza+d8P3zZhKeloUT8dBusmpbVTIjdyCX1j6FDrN8NCCGaw9F3rJ+jRdVb0txK6wIQ==,iv:jY/lvFtwyu6QHijw1ONX56XXCbDRR4jH2W9yKeurhZA=,tag:LZ63U87g5C2O5d+AEU6lcA==,type:str]
kind: Secret
metadata:
    name: github-alerts
    namespace: observability
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlY0FmWmx4dVB1djJSNWh3
            TjJoaTNNUkZKcW1pdUdGWDZVV1VyU2o2ZlI0CmJLaTRhMnZ3ZVE3c0VLZmlFMVJm
            MXhMM0FxWkRMeU05bTg1UldBMTFtRnMKLS0tIFBvcXZacWNJd3MzOVpXL0orc2Fm
            cCtLeXNlQXFsYlBmWHQ3WnErcTBOT3cK/b4Bo4Ov3TVLIAs7+73d15U4cfCUIwMA
            1duYho/s5PZP+wrZHBqj+9vMtx+p0bCAyMbD9OFtamDDdgKgatkvcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeXljdW1sMHJTVVQ1N3JO
            Q1h0czlDVHh6bVMybEhBeEkxOG1yVFlTY0JRCmhrUm5NZVhLZnJmd0FoTm82QUF2
            TGRKVEN3V2htV090TlREUWxGdjFPN2cKLS0tIHl3YVo5UytJZGNOS2NvL1ZzOEpW
            NGZUL3EzUjdndWI5bVhnUDVDdnFhOFEKEoG0etVfjFI7DTV5FYqfOXVZzOr9HnSM
            pf2gvBif5Ptt4LBRf7xbA8u9cZ2udVGpRFDjZ6RAO8tt36B4fM7e2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T07:23:30Z"
    mac: ENC[AES256_GCM,data:/1F0c+1vgy5G+xqlUR3Gj5YQYo9hi+zuRboFEGCcShbjTZjS6RiYOwtF0Pa5CdDc0RJsgaHtZl/oRfkxnPcTPBFQu8B5FWM2FUfurCLp1EXsNQhxSaZAiB8rpWuEM6pcve26+uolMg3ca3RYoZWOitWdOKxBZviatbHAGEN1VIQ=,iv:UFyXtFs4793oJ2ASZaZ/CeCF73UgBszQWOMUiMocr0s=,tag:mbv5Z5nmA5iXW2WQSK7Whw==,type:str]
    version: 3.13.3
