apiVersion: v1
data:
    clientID: ENC[AES256_GCM,data:ym3UTNFC/Ljb77NiCMh0BFjcUz62r3g6XME4Ag==,iv:kIxN+/mXs3aeMG5dWnKQIDd4VMb0RtYYhlOc0k0+vN8=,tag:oIs6H6O6Ypv3h56OlMZVIA==,type:str]
    clientSecret: ENC[AES256_GCM,data:Sss2/5rSDa9a/n1eHHjBtSkZQNUMWO6Qsaoi7elwbTRgBpXjAGVWFQWrkXfmsfOOLLjhoN4n2Hs=,iv:JRzfpASdX9V8dcbMJmKSb2iwTAhyrvNklrSipt4yJkc=,tag:kvw/+cwdV6Ygg95ShNTGPA==,type:str]
kind: Secret
metadata:
    name: grafana-github
    namespace: observability
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZVYrZktlSTN2MUNlVjlM
            WTJXL1d2by9UaGttV3h1Wm9xWTRNa29FcGs0Ck5BSSsvajM1eG5aQThpdk43REtZ
            Y2RXN01FUlJXNFhDRlljbHhUcFVTRW8KLS0tIG1mNFRXMkxJT3FJTTV4bmRnbjF6
            U091VE1EWDg4a0JVd3dhVDlEbnVlRUUKRLtukCYXAq6ZEDwU7hWBMexIbTWHnQIl
            Os/pqal0HoexogY0wzTVN1cOX2yRwgL4xDNxuJfOw/d0+q5X5suxpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQkZXYmhmM1U4dTBvRSs4
            U09peHZRR08xZDdndzFNM25qWTFYQTllS2tNCmpLVW4xQ2trelpXbGplZFhDR0hR
            eng1eFpyUm45VWpHQTh4YkR3ZHFhVFEKLS0tIGtBbVoyN00vUWFudVZjZlowK08v
            M3gwc1FTQ0hzKzl0dy9MZTVaL3kyM00K537pS2lwPg0YO3ZUVFa5BSKhWjDkAsGL
            vxjKXm2dXmwxYw734N+2JssBdiw3H6suO4MHGGshP3a0NBB5p2D0xA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T16:17:20Z"
    mac: ENC[AES256_GCM,data:Px30ZLPbMqPouAM5/I+LBbjIQ76PT5SEUbq+iZypUOt7ketovH8FBnpPFE5GKTLCMHenKaDT3Sqe4thYqhM2OUWJhf++/YVsV2HlVSwB6S8QLoFEITvtUZptZ8Rcz0Rl2X/j3GQkanUmtnrJoyIjqaBk5T1nnL1ItoFzcXo+1TY=,iv:uoLM2xTVHTSuCbdsvf5Nb1FZQHSJMqakiqsynd6T8xw=,tag:+Ae00CBGNt2w2UUW24qDwA==,type:str]
    version: 3.13.3
