apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-github
    namespace: observability
spec:
    secretTemplates:
        - name: grafana-github
          stringData:
            clientID: ENC[AES256_GCM,data:8g4wl2Ze7hHcrfdLqSakv98zMRc=,iv:YZcTlZmGOHVZsyg7o1mA3XzaZ4tXzaW3LXr44Oc/LKk=,tag:GD3+KpHg/j78ZsFbr8hTyw==,type:str]
            clientSecret: ENC[AES256_GCM,data:CIeW8McrNjh5ndK6NidFG/SJGigH5GceulVOvG+IkqaZx+0u+vPZJA==,iv:qoeTesFr/qkv1se5O182crzAQcFvZPCNfJO6sSFpWAk=,tag:J+6CLRkWba0p9PtdhIk4Yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNE5SUXUyUnQ1QnZhRlJ0
            ZDNXVk9MWUZWS0VNNEo0YXdPeDF3bHpycEU0CnBUbHhoUWtjUHhobnZPeGxvQkN1
            aGRocDVCV2tYdlY1ZkJ0WDRjd2NtSTAKLS0tIHFHMjFkNi9yT2o4RG9aNm1FL3R1
            LzFSOVg1NGk4YWpPREZ0RUFWcitabUUK/70CD4gw7byM1XKiOn6Canw5dXQCMUEV
            LtuaDrb4mwWTnLIJjwHtxky2Qw6ZWUj5TLlAIxAfsrPoxEA1tS2OrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNXlKSW1BQktiTzBmU3VW
            SFpRTzg3bHNUdnBHR1VQcmJxc2RLWFFSQnpZCm9MUFN5Qlg4Y3RQcDFnYVhoNDFD
            NjdRRDhxWDFpRjl3TWxjS3IzM2pLb28KLS0tIFBmOHVOYndiSG5lV1lSTUdxMVRJ
            Tll4YnlrN3pLbUFOVkFOaXhVSnNvNmsKirDUAClIpfEUKCGO2VwjprB2QDlZmo+z
            UJD3Ar/hfFBgTHNZPEQ84YMFVNeJlhigfRv9dZ6vmjgBDUwfwM7j8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S0ZmR2Z6OUFZMURkTnhG
            anZ5TCtldElNRHlONGxRLzlHS2hSZWkwQ2k0CnlQN21kQ1JKK3ptMmk5b3hzR1ZE
            K2Q4SHB2elREMTYvVmptL1l5cEtGaDAKLS0tIFIyUzhzb2VxOThPWHpzTzhxR0Jl
            T3VXUU5JemR5MktWTWxvdUtZN05iY1UKpO4ejmVgylBfbplSptlt6SjBsrKFkui2
            Luj5VUmmmFqTX/p8M632lmbCuvgxixx3QYVjyjPOJwZkwwlb+1awNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:14Z"
    mac: ENC[AES256_GCM,data:hdKyd8FYCqLae/pO1t9y6WEyiaaWZevbm/ldDe0CAey6szNWCkGLDsUmVtIbIdR5DI293KG4/eRKtcQ/YO89Ag5R8zFO7rMUf7/3zYmZJyAmjp07QvqtOcE0OYbZMhx/YyeG8ra1193nEVAiKs9ypswI9AQQ4uUexT4sMFsBdkY=,iv:xAIOpFF24K0B3dhp10qo5ihgm7NQyVSTc/RzbcUcgGQ=,tag:KKUWnbe1h2/v2WIJqREzKw==,type:str]
    version: 3.13.3
