apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pEeabcfFjz9kXSsZmKyGpLSCqLBSsAB6tYBX/A==,iv:f7YLuK9hFmBNOAjX/hawxXXNFB40h6fX/AeIlXMVElA=,tag:yP/K6VIfaW3dWC7wXsINcA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:uv5k+m8KqsA=,iv:4RI+nM3NLzaX0gaUql/qZpETTylS1vpwdjkXeUivFMo=,tag:vXsHJIlSV1phpPayyUFmIw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Pwu9cdXKm3jg4WqIA12dunWjVp4+jJdrloZ/FrUOwIqlkCjMnJDs0Z+9ifBb/bG/HSXH6cw7weU=,iv:T5aQhqI3GmUBRzgm2yAjJiebSHF5NfCTh2d3x+a9GpA=,tag:hRGqyK+Qcn8Ogj/QDEzspA==,type:str]
kind: Secret
metadata:
    name: logs-backup-s3
    namespace: observability
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b3VOOFQzS1pRVG14Qkxk
            YnVobm1SVU5NcFg4ZWFhZTNkVTFBY1VnUVRrCmpPL2d0a2RYbTU2OENmRnA4VXk4
            VlZOZ3FqNzRHK0VETXFtYko5cjBPcU0KLS0tIDB4WVhUdXhiM2wrekJtWUplYTFm
            K2F0SGVXKzlueXJ3RllkWGFibXdUZWsKPb4lZjiBfnYcXekHEYBioGQRRS028T2U
            EzgjQPjNa7qywkhHzLn255DHIdd+Vt/HKBD1trcwJbFbU4rbu+lV7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUlplakQyUWZWTGJsRTZx
            SVA3NWp6Q1A4cTNqYUJHYkpaR0xvWDk5V1dnClJaMElnQVAxWktkVUdwZW9SUGF5
            QVlNSFVTVUkxTDBVZm13MzVUN2VIZFEKLS0tIFQra3k2eUlTbFpIUVg2TzdDU0R5
            N1dFSmpiN0hBRW9yeHZxYWFIM04zQ2MKxxM9JJ/GBjaDuCw0LBBbpPrLV5E+5Wra
            blPbacvXkWcbr58zxFiT6UDS1M0Ewcq5yY4gSvSlwuPpDzM3e8MZtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:58:15Z"
    mac: ENC[AES256_GCM,data:3cc1vYr6AfnKIUD4nNUVn9a8/3yxOMC2bJVCltsOldJlAvdbxyvuB71ZLoDLQdd1QJrmtv0/Ax61Tx0FGSH2zX+AayKyUe3qMMm3keN+mYqGCG0iE+QV71FeRq8anxI5SkmmnnQ6G6tMKmPAhznNZGMfBam07yOor/hmIRFGCek=,iv:wNcpHNQYNQZ/MN8cmXcDLPJw48GAtc/eGn1Wjwcw7Lg=,tag:Z8Bn1oJFc24OUr4IT3skFA==,type:str]
    version: 3.13.3
