apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: logs-backup-s3
    namespace: observability
spec:
    secretTemplates:
        - name: logs-backup-s3
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NSok0Ep1l005DfYCMx5FyJ7I41A=,iv:xF9sLKEdZ38Zebmd3p0bGpKJCVlzyd7nWWOLHa2hgYw=,tag:5bl55psnzseKLo6lMrQ3WA==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:UmhbLw==,iv:vZ2vk5QTs35zhBM0Jsk+EbhGsR+ndjCCURbbeEV2jfs=,tag:F2AVwuV6HJy5CAoOTRFEZw==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eZxG49IZyxDrvsssL6Qt0OM+jk1YclxofezPZfS08SZ/H7NL+3XIfQ==,iv:Vs4K0+KtT4TtImpW0RUl5Z80SBhRVg8XpznqFA41JPI=,tag:PK8kgwGbZjCaKdKpGy3ixA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVzh4MjBkRDJxRG9MZkkx
            bTc4a1dHWmw5QVloYXVhRTQvUGdUOU53d1E0CmdWYjd4MVI4ZnBSM0xVRTFnNzdi
            cmh0d0VnVG9LaHF4Yy9qM1h2eDQ2MHMKLS0tIExVRVA4NEJYVjUyYWdWLzJ6QnRP
            SjB2Uk1RWmJ5cE1oaWtVR25pRGJ5YUEKCthdeS3QQRy4Q9okaIcD0edDJj2dKOTf
            7jUdC5ZkhHAeIQNfaQ/AKjMHb9krGaM8ZJX3B0SnagHoI4ye1hzreg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NHhpQ2I1RXRKd3Flb1dk
            MFpUUWU3akFxSVA2UFM4UXZSeDl4cG0zdEdFCk1ZbUlWb1lqYTkwYW01TGplNmIv
            MjllV2xPS2c2RnpyYmlQOHBKTGVzV1UKLS0tIHJyeHl3Y212dmtPU1BDSitqZThk
            cldQVC90ZWoyb0c1eXI5Z0lDQ2IzVVEKKaQXIg4x4vwYftI60TJl+9Blh52tCqHQ
            +hznXmRV8HaWzJKlg5RZf7GeXNSdVgcIm1k/VlioDkCMiCrlK7Hr2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYUNjUmN3Z284M0VyalI1
            Wnc2TDQzV01tVkNWcTMxZHNoZ0dHTmxGMkJvClF3OWRxVCtjVFhQd0VCQkFYZ0dR
            YVNZZ3I3K3BURDdHV0lxY2tpTk16VFUKLS0tIFFuRExvNStBaUVTUzVBODVVNTl3
            VkRya3YyTWIveW9qRVB3cTR6Q0pKRFEK+e8TeJI3xaYL+cQWlXRXsWMW6df2perV
            hrkTAJewMt2fhsMQc1Ti3COq1XSdOny8SJYwY7x9SlFD915F+36l/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:16Z"
    mac: ENC[AES256_GCM,data:0WcbyvedVlm3CcKUfL9OoDN1f6V0ykl49oBPTPTjDs60V97zgUlOBmDuKhOXoKiYZ0ktaJUAMgQ0qYiK4kmz0re+z2UmEIskqi/34BoRAhyVUVF6cA23a1C8eiSA5MU3oePCVfmZt1baOxGhzYd2qA6jBTwAS5QY26IB26RlDdI=,iv:+5LQkQY8Pf9eOqPYZy9YZvzED4jNKg1kye/RGWfopq0=,tag:iJ7ea6RT5HQ9C2HuKaXohw==,type:str]
    version: 3.13.3
