apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: metrics-backup-s3
    namespace: observability
spec:
    secretTemplates:
        - name: metrics-backup-s3
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lUQIRy6ier68P8qvytylxA46gWc=,iv:0adLTPFhj3zy+8E80xBeysc3QGQedmCkjXP6db6SkDw=,tag:Ot20r80w+FQzfCjcinpmNw==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:rMcjWg==,iv:ov/+EMdTNhE+KZJu5ePeFZWsQdOzticQhocHqFg/9uk=,tag:N+m9ZFyM+p4bRm1zA/M1PA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wXVpXeESOB1ONfWKwt8ePpdKxbqe+fEK859w4SYyzo31wFobs0L1LQ==,iv:GE/yDlZW0kU6v4UwpZLQSM8ITifjAm6BcuumA//CZtE=,tag:yU9765KQith3fUhCfgCrEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWlR3cDFQVS9PcFpzcEd1
            Q1h0YWIybmJIeEdad2lHSGh5NkVJSjNZOUhZCkFkM3FjV2ZhSkhVbXVGMWtFbDc5
            T3FkREtFazBCYlRDaEdzT1ZOWXV6TEUKLS0tIFNvUzEzcENzYUNFZE9HTVp5Y2lD
            QVFlNkUyVUgzVVl3Y2ptRTFhODRVRzgKbaVSfynqOmlbVmi/5KVRdDXhE/rYMAbt
            kmnqvTWh9rM60OGr9tvdSLfq6jMRv9ODm3krpMphOmAapZpPJslI+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V29CWjFIamtLUjFMOGg2
            aEkraURQV1VGNElUUGM0bkpFaUNsL1JjZzB3CkpCektMMTFjeTc4Y0QrWExaeTZi
            cXZaN0YzZkhaZ1E3VDhJMGdDZnBLbUUKLS0tIDdQYnphZEJwS1g2d0NDWjFUZlBs
            NjdLa2RlV3VkbVdvd1JTMElvQ2oyK0UKj7m2H0bIkoAM+YufaRiCx9LooJta/UTA
            GWn+yByDuxTXRO+hOB0twbfwa94GRYsjYb1JAdbgmMUGM1Nx/yzHpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SUc0K0w4VjIxMUN1M3ZJ
            SklFRkdlQis2dUczT0IvcGtUUFo2cVZaOVRZCjB4RGs4UTV3bmFsaHJseWNEZnBV
            WkYrSXdPTUtZQVRab1hScEI5bUlWdHMKLS0tIHYvQlNhK3MxT055R2ZudzJIdGRM
            ZnVnbFJhQnlsZERTc2Fyb3NIUW8xTDgKn5V78Ang5p0s8qSjBFCc+HSsX67D02Jt
            cV68htSFHVqDengp1+9u2GxZrk834UJqzni01WCoNs5Z4Z1VWFMqxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:18Z"
    mac: ENC[AES256_GCM,data:ziHjalzT6Blgn/rmlMHqAWxwgr05Idobd6P2jr4hmyqAA29h4SlG5NQW6AsM87J5LEfv3wlDk8wVSUMJOAozLd1bCEaKqYmceAo4WkaD9brrEdmC6PMbTkskMXxP+qSJM1u/t7O6CCuAZwkwQJLtCZAS6ccralkTk+BBRaFYKL0=,iv:efxjQpRHgCCtrsqDwfClLYzAqqE6UkKhyeZ0snB9OJ0=,tag:Vhn+S0RyedO3b+syrS06jA==,type:str]
    version: 3.13.3
