apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N6gaCpENfs9kT6ef4piygFtHgfTo7L2+ZCrc8g==,iv:Hwf0YDRVmTDZQQ9gAxfAuMRP9VCZe+XBxRQZXVLoD+E=,tag:Dbr6DEhFnHPbpkad0TjBkg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:AA97XsfKHwk=,iv:fy676n0c4mT6AZVHz4iDxmXLQcELjHb1W7PIM7Et4yc=,tag:Z2ij3WIQZQajFMdMUbTakA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yAn1f6cXLPbZ/Z6Sz8iA9+ojK3EDJjofSVSyUJqpagVum4LGxHdxRfA4Tl14yoeNPKKhsEgeeYU=,iv:U8pHOLWSnAwGNokNgJub8yL4UKRERD6dFFFahtB5+sA=,tag:WLDg9uFIUl6UA4useLeImw==,type:str]
kind: Secret
metadata:
    name: metrics-backup-s3
    namespace: observability
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZGd4MnUwcDhCNXJxS0J3
            QmxyN2RNYjBMR09Mei9wZSsvVHNLZFBNcFMwCm5vUEh6YkZPa3ZaV3gwbWNqOXRW
            N2svSDMzTlNrL25qckc1enFpVCtEMXcKLS0tIEdCcEFtNHVNM0FQTk5JUFc0dTZl
            WTliekV3K3lXTkZRWE9VeTg0LzdKVG8KmX5DX+NN4GqiCvRhmiYf43HFXkwMXH1k
            b/bjTwfE9ce1zayX//vKPcv09b6OlUb80T/GkdD5MPQOt6NYVt6sTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OG16ckFvZCt4L0cyRytS
            SVNrK2VJOWR3NVB4Tlp1YitxdkV0bm9kNEdBCjlQTDhJOTNhckdVMmNrNkFCVjBw
            a3JWYXhyWStRcGZGSWxUQzlqVDBaNWcKLS0tIEIrZnpiQVBEcVVoRzBpdU9qcHJm
            V1QwdmdYcGtBNlBqS0FTNnRvMVZXZDgKnx167i9t2Dd2afgt2Bqwb6e/D2WFyuPE
            OfdlIyBwa0TPlHOb02qg/1teiQiIiEvYwrezmsiYAQQ6Rc6pdp35uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:58:14Z"
    mac: ENC[AES256_GCM,data:NxNxFa7UszkuJO/niEskyPZv4V9tzn/MSTmlxspNj286n0IjRwjUNsfo2r/LSVvIE/50vTo8ftUh9jBgOB4rWcKCTDTuhIbJ0UVcGEjZrDq9rEYLj8wos+snBianQ8p2gbgFWLNoL9BAH3hNiLxtYr2Z05m8L2EhRPI8Xb1x4Hg=,iv:vGXR3KbCAM6kjqxOZCPfZCED74UAU8gbkAC80oUuBEo=,tag:4OxeapFfKIMObcozlR0qtQ==,type:str]
    version: 3.13.3
