apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:hBK3K6LMBmbb8jcw7aglLJLvnanyiU7PQHIrmQ==,iv:SlXy+J3U05tPE4SQvy/7psrgnhpjWsWAZVMfd17ygiY=,tag:GT6h411CbSR9XwFMD/A1Ug==,type:str]
    client-secret: ENC[AES256_GCM,data:K+up3Qt79vcGha25Zc+TsVFmBt625ueuGeXKBFOGwgjeF37ww2zX/Lq/jjvHjkd8goOh68aO/Cw=,iv:Yycl/87jbhH3CW/kk2VvyX6tojtk7zYwMDc1bVAvXuE=,tag:HCRn6lxHbzNT6hRIPkFQqg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:FYe2ydW9yxGUYedPGPqPoNiPjMwttRTCCevxIJBlCG3Xy8zcs0QNBmdPa7g=,iv:APWVKTdoTZXuVtALuLbkUQ47GtycwWQ88A/ldc9ahPI=,tag:zr32MlPOi+NcAHdD/AmCtg==,type:str]
kind: Secret
metadata:
    name: oauth2-proxy-apps
    namespace: ops
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWTdLbjZVcVZUckdEcHJT
            dUhNdVVPT0RZbEJJSXUxU0ZIZTZPSlEvcVFFCkkzMGRYdkxsWElHZEpkaXNnOStM
            aE1ydzNidlNRbVRvMlQ0Vy91Z0FKYWsKLS0tIGI3NGQwRHFELzNUT2lPdUcyTXB4
            WnBRbDhLT2QzUzkzVXhCYzlTMkczRWsKG2sWWjit4KTR5t/AhGKz9jnZdh0/FbaH
            c5gDvdqxAiRkQqmDvWDginJHjLhsYHgOjEPFShOXBy2xuMzxHeJ0UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cmVENCtLNDRMVEJYajhZ
            R1I2N25qY25vY0l4cWhiNmdsRWtqVHVkUmh3ClNVRnRvazNxR1pzSExXbVY4K1hW
            cVFHZWtkS0ZIWWdtSHhxSDlCWmVObnMKLS0tIGxuY2dyMXRzVzV2YVB6THV0M0tv
            OVF3OTNYUysvd2pVdlJQUmVGcVVkUzQKjJ5h1UCNOUTTqylqI8EOzuYeZacbFSMS
            0k0rPoVKS5ze7ycE2dkoHBkeTp+lqydCiDefvSdPKK5ytRV+5rphZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:03:44Z"
    mac: ENC[AES256_GCM,data:8tikBxyrtknSuEq6j2Se8jttn52EK+x01sH3l0mKjKBzam2R9Zb67Zxk9LImIX8dmbX6QUyU4AuEvrTNSA+drhlBZ4ZKCJzn9UYiDAyNDACmTxg4jkGApjHlQWh6BGhj2mtLUSB0bCqItVLgPCHDcZNa6L5hYBgRuSiEYeVWKIM=,iv:9rSLthqRvODgnc/gfLsIxn72ZaY60yBDpdGosEwdxrk=,tag:Vgh/+6jmJI99YginybpLWQ==,type:str]
    version: 3.13.3
