apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: oauth2-proxy
    namespace: ops
spec:
    secretTemplates:
        - name: oauth2-proxy
          stringData:
            client-id: ENC[AES256_GCM,data:U3rv2OcE+hdkbirlcjssYKTvfBM=,iv:3T994KI/Qv4xWwwr8Oh//wGhgBMZ+76vmVceRxMcT60=,tag:lCealsc+aNLZZ0w5W2dIWA==,type:str]
            client-secret: ENC[AES256_GCM,data:aWa8m0fEI1qonkbvGuzofsOwxXeUEiAAXqSRCwpkJ+TA/dg18bdg9Q==,iv:i+4QZ9dLgaeAaN7oHBxgE5u43PXFXWApstxl1ZFSOhc=,tag:1dfBUiCvyzK1kJsH3sJI6A==,type:str]
            cookie-secret: ENC[AES256_GCM,data:6/DfrT6ROEpBcu+etkP/9Jr8KXtq8Di47SGvuBonc/0=,iv:+NLJMY0r+fpi8r2xHtEhgbti/agChBkY+DoZQyqaqbY=,tag:aIrZjFXIwr2x6/hHGu9ujQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYTdEdUprMXNxc1lsQ2dK
            Zm1WZmRiaFFralhrL3pVSG1OczRwTlF4RWtnClJGaEZOQ2phVVlOM1BnejV3bWg3
            TWhDdTk5a3NjY0lJWVFLVGlmSnI3SjAKLS0tIGd5YmJNZ0FkaytGbTgxeGtKVFBH
            d3BNTFhFZS9BNUlFVkEwcE1wYzFTYkkKatTkiTbCUUVoMvl+PDV1Wh/Oi+8WN9bj
            6zBjaYbUMGpjZzd5DMTJ6nvkl2AyYT5VMBLMlJPVj93EPdN1CTBp7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOUpCejRUanZtSHZFSk5B
            WkozRUxFbXR2SnIxWWFHM1hkK0RwZWtCeFdNCnhtdUUxSUQ2M1F2b2doaHp6WXFa
            ZG5Dcnp0dG1SSmNMQ0VKTVowc21HMlkKLS0tIDdCZzU2TXFsNW01M01IbC9oUGNs
            Q2YyMG9KQVJQdkpQZkFWRG05akRuSmsKcy/RBL/uqPn8XjVb8vdnEETFSj00EjHS
            seNOYKvGz0LwNdnsVQmEkDH2XJkBjcKKYFczWVKFn7OBTrKDFhmpZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RWlyWU5GRkNzYk5FYTVK
            d1pxZENKenNRUHVyTnAxVFJpV3dPcVU3QVZ3CmpXdTQ4UmlFampPMUdIOTVQTkxL
            WE5odWI4Y2JSVWhkMVhtWGhGcGMrZ2cKLS0tIC8rc1B1RStJVDljSmdzN1h2dmM3
            L1V4NzArSXJvQy9McEdxa2x5aGhvNlkK1kQlkDJocNbxa4BOUbwXuNLgKL3//dIn
            14vWuVFS7p8cWq0nL1mGgHHUr7YIvAIYcqYJx4977hKg+pNrhCtYKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:22Z"
    mac: ENC[AES256_GCM,data:nioSfKmy+wH3XzGUX5eTz2rFlFgDAiQmh5/GZZYjSoIjrHIsQ5WJ2krKVPKeqmt3ZRjh+81/KZSlKiOJtRlHGoxOTgvWi2NydsG+WIyCrWdjvSrFBMCumwVYhZ7PN3wSXdH0CTfmxnmor+hP8JhdqLHPQ8EFPPBFNymXE/XK7GA=,iv:WUyuqYddROsEz2h0Z0P9cpZ9+Oj3CYHJC6uOIDaZKXw=,tag:ghzS3lauAvg3XBf+56fKfg==,type:str]
    version: 3.13.3
