apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:opupDYVzCs4r6HxxVRZVe2GvIdV6YRFjFKp53A==,iv:KPNvKSr+r1bfZN8uc8Bn5cA/HAqzmy2fb2Vu9bob6S4=,tag:943nBuYRiZLVVDIaIA5EFw==,type:str]
    client-secret: ENC[AES256_GCM,data:Ymv/WQ+2EA+YSmcr8KY0t0vKheqV5HsYDBLXuak0VdBHYiyTa9+h7mzq+nzSrQYTuL5dpSnmwiE=,iv:p+qlf/HuX0LBDOIGCBP17q1hqwZiiUx8z4nXD8jasgY=,tag:djm+iKwoGAZ8v5RGlTAXAA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:voKYHw0/C3TqpmM8G3qcSBjzj+c9wh6VzMHEEcWhu+fQHx5MfTtPVJh8+pI=,iv:frgCszgPB4tAnZor7JXLZhe8V9yWmGjorb6uNMpDOtw=,tag:xt74vrorsTEDJiqRJlKkzA==,type:str]
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: ops
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpalRiT203MmFXUVhpUTFv
            c3JaK1ZQdE41SzN6b28zeWNqSDVDdnJ5WkJzCkw4dVpLaDc3Zm96WEtYYk9CK1Jw
            dnFDNDREcXFuc1crMW4zUkQyMWpIMWsKLS0tIDRQc0hxVG1EbE5QSlV2eTdlSnQ1
            MFpLRVZKNyt6RWUzbnRWc2FETHlHdUUKsD5e96jHzkgNQUKQrEMVOqEA42KbOHaa
            fCITV+PjUXkcBQuuRBC+z+/45az68Z3FM/XsPF2WXgXu4FtE0Iz9cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RW0wKytEZW4xV2pJdnRz
            OUUrT0dnT3NuZGt0WlpjYkhtMEZmSURzUVNNCm5VS1BlOXVsY0dTZkp1SzFUVmZD
            M21IT3FMQ2F2SjlLNHgzU092b1dTM1kKLS0tIDFHNjFzRmc1TGlkOTZDQkJOc0tt
            NVlnUmV3SExENXd6dmhwNXpOdnVWS0UKGyDDN647UuXw1pAjcNmIIXkfTWyWnpmb
            GU8ddODWvr5sg7MnUajO23kdN9r5Us7F2vmiEPZ47w4apNY85acLDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T16:17:20Z"
    mac: ENC[AES256_GCM,data:uh7cnvPegU74hkNtLNNwS/dk3pLFjgaQaubTFQ8Pz0g/QqzZta8H/fkl/3lo4vNHxzbqWIBLiGwtlxxYrQWI62JBamTK05R4k4fHg16CTvneBHHFV5XFTVmbWjzd9a8CsO99m9NAPelQhTZ8Vgz3/3bkxrO0hGFAiTB/0gO65MA=,iv:MNVD4w1zgfMufHaaucLaVxDkgRqx0WVmv0zHuc4QFzs=,tag:LuxK32jIUGpmlBQcAFxhAQ==,type:str]
    version: 3.13.3
