apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: oauth2-proxy-apps
    namespace: ops
spec:
    secretTemplates:
        - name: oauth2-proxy-apps
          stringData:
            client-id: ENC[AES256_GCM,data:e7hUCw76BRqWk49tlZ+zuHu7cu0=,iv:p+s6gY53+vAOgBFmUU3MG7tXETNNEwwBcJEB5FcvJ0Q=,tag:pBUVFAqKi8Szr8cjirKJ8A==,type:str]
            client-secret: ENC[AES256_GCM,data:887NLl7uBI/5vWN3md9uKjCkpmng8ixcM/hbBhGpPScG35uFrmhjLQ==,iv:qWCVYMSQMTgD9brGGghEFTlCCrBAtyxWlG8GjQVmY3U=,tag:Zo2j0Tqm5zVCry8GKRLYXw==,type:str]
            cookie-secret: ENC[AES256_GCM,data:MhRF/l3562Z2Lgy9GrAHn+w46W4egcntN8mbJ9eQ7O8=,iv:oZ3h+Ky/KDKq7AQopbSxjdPhR6dIUNUgTA1oZkwRgvs=,tag:NeCwfJ0rQfN5ZXNvN0HjSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV0hhQ3BONVlsUGdoYkpy
            bXpsbE81UW8zbG5mODcybStTYjlsUHlyd25NCi9ScVZGYXp5NUVnYWQ3WExLdVNO
            b3cwc00rdGpQbnEzQ3VtY0xDVmFqa2sKLS0tIFJBUzZaVDRWeWpyTHhUajBrNlI3
            VXZMbmVkb0Z2RlNwakFHNkxCWCtlSG8KyQSKX6XkXtA5Szy2MeQxGvh7zLEIPJUi
            eaXqu9VBuwRDSzYpkUqj2jv6A1aHAIGeTgAq7s/U9fVM+F0ZIo1g2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRnNDR3pEa2twNUJna1F2
            Y1kxbVV0NXJReWlVTjNHSjZNc1ExM0ZsaEJJCkQxc1c4ZGttUE1ySnY0N2dwR2lR
            NmJ4WWp6SUQ4VWRvSkNZV0dMd2hUWWsKLS0tIHB6Y0Y5RmdrUUIvMkRTNUs5UlhH
            OFRlWkVNSzQxalhIRXgwRVZFOSt1clUKnNK8RlUsv7hVxhdxlqeOJAuf8TC1sdty
            0ZbM68rHhaiEkfrQx7vWRCVgcN/lRUoqvz68jxQHoZ8+NTeKJKZCtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbUVlOURxU0RveFNZZTIr
            RHd3SGZpa1RlRkRnRlYzbisvRnRlLzlkZUFjCk9tY3pnZitzY1cwMkJRNlRpQUwy
            S1E1NDB2S0wxMlYvVzBiTmo0N2UvdncKLS0tIGZMeHR0Nk5IdkRqcXE0RTluVS9o
            UEMzMEpBQ0ZBRjNvYWJHbHc0cHBLeFUK43JfMSASFXl+YWdl8qxhPZUMHV4tY7fA
            2MzwZdneomTtZDghdYDfPa3aboVZhCSkosytsh/rW3PiN10kqj7b0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:20Z"
    mac: ENC[AES256_GCM,data:ZjEmcCMCAcAq8hbQ6eaZ04hHH60YW1sREP9AqNoX/ufFANkifizZPx9CKuSOzm+glq4i1bg09zIcMFaGnrNE2LkEZ+RMUtpW0MAKsr6T0EeAQ2yQrLumzsOL/PXiXn0B1HkXOXBdaYFM+N4d41qMjDg0HwR5kJrrrp5CwtmkLe0=,iv:WCBahz49E4pT4EOyecFs1XwiL3itDpir5XHC2cJZ/ZA=,tag:S9Xch7+nfmk6YXti/Stw6A==,type:str]
    version: 3.13.3
