apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pOs0IBy5Tit08A12Cja0o/+z/YixV0rzY5c8JA==,iv:Is8VgVgN/XDC+sj9G+g3U3anGa+JU+EMaofo1DqVMdM=,tag:LV/HfcyOf2fb7b+dTemoaA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:bBnam8SRv+I=,iv:p0XwCkTLIxkuGGwguNh4xKTtBI1OYDnAY+CLynDa46k=,tag:l5SBt+uax9J9kzYOrmqoFA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CH6+9cQwA1rLiFxTcIyIteZMnoPqnupla3myjVgrUONQ4uAe/s+xbJbqpKfepkMkjOCevu6dtTs=,iv:/rfMBny+kkSNgCYcB+zH/LQBKAzolyn5P+ZgAErlwxs=,tag:aazSZOscOcs64RCPRlDoiA==,type:str]
kind: Secret
metadata:
    name: seaweedfs-backup-s3
    namespace: storage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOVNSSzVjOXZSYUxrcUdx
            cmpQWXhmQ092dmg0ZTU0SG1icTdZZWRubHhJCnl1L0ZMczFrT0ltVzFYZUE2d3lJ
            QmpyNCtlN3VoUmcxSWRybnU3K2lpd3cKLS0tIHhmRW9haTdLczUxbXJ4M3VEdUFv
            UkJtNFFwbFlQMlkxYk5sM2xaU2NXR3cK//+ZIBVdWXGpUjUDH36bleu9LhCYzcl7
            4WMqCONoCtHIcPQuyXcYYpl3N/03v1yHJc+Gimn05JWuISw82iGqDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ck0vVmM0ZmY1SDhtWFlP
            Z1BZaGplZ21FdDNOdkZ5YTNxSnA4QW1ZZEE4CjBQbFpvSkluakIzOUcxN0o0MlVo
            VnJyOFZJN3ZlRzBtby9vYVIxbVRhaVkKLS0tIDc2NDRwSTlnWGY1TU0xN0oyUE5E
            MzVIZm84VGtHdHpSd1IyM3lXM2lxWncKig582dqBE3PjlCqrAO80YJ0jT2BenH/w
            EC3AOPsiqnnR9dltBlnsg4JM1YTnfinfz07fcVTzJPEHIQ6jeNkv4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:58:13Z"
    mac: ENC[AES256_GCM,data:AerObdCMx1zMAj8d9qYdAJ8sGrGb7DvDsa0PtIMb7oQlyvFDgjYDYYrI8W1LcEiw5uRyoVqNbERIOQ3kNGl0Ir7EaRoGQnchBfhIK0iErPAcWn9rwZ8CH9Vp+xx+Vdr6D2XrJLtcnk2RU4FQQVlmz/gW3KCV/LX8mfkWHu2o1zE=,iv:LONcATYSKAvtQtFPM+g8wZJs/MADqx6TOCnLVI+iz9E=,tag:3ugjnlcET4rcJ4n2qtErQg==,type:str]
    version: 3.13.3
