apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: status-heartbeat
    namespace: observability
spec:
    secretTemplates:
        - name: status-heartbeat
          stringData:
            token: ENC[AES256_GCM,data:HE/cUIgdMG18dMYTOvw7m7S4Xs9U3tGUpssNLEsztX6JsMvwDqOyed+1hxGAehgGU24en+TBmDmQsG76Eket/Q==,iv:vUmRT/EsrWRBIZdCOfJFUc25YQVQ7gNtomw+VkbxQeA=,tag:hhfE4V3aXeoBb1CKO+XsCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QTBiMU5SN1BKMlNyNDBL
            am9DNHdNQUR5cEplY00vcFpqQVo0dWZGdjA4ClJpT1BYQ0lYbEFERTNuTENuYlVZ
            REVZcVVsVDRsYTNHNEVKa2h3T2o2QVEKLS0tIGgzRkJ6bGhyaEYyQStzWFk0NHg4
            NXVPd2NucGdnS0FzWWZvV3pXdDhmZlkK324maLBubAm70itXnechl1hitQqzGzWH
            ZCz9xjk4twbiC7nZKTwtiNw7yVu4mY+xBvbcJpjGefQhooZOTf60zA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RjZGTGt6aWZRdit5SXhN
            eURYSG50dlliK3pKVkg5R0hUWGJVMVpZbmpZCnJRK1hxUGJhMUxoUWxWYnpBTnFN
            dWtvanJja1BaYzVtanFCaVZwR0h3NXMKLS0tIEh4a2NCZjNBelV4L1g5TkRCZVJQ
            VlM2OTdlcGNKbXlqV05IOWZmcXcvTm8KPP7U7FupYyfytdeAi4/vFaXnw8vLOz92
            Mvsr1hhE0TvFIVq0SV8xNaNMXgV03EHVpAc8e6SfX07jS0P8fof+bQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMUw3R3p4bUxzbzA3d09w
            Z2x0L2w0czBwcWF6TENNRE41SUpka3d3R1gwCkVqVjFlVWxwMmd1VTNvS1J0Z1E3
            b1BEUmg5dXhzOVIxcnZPQlJwTit3SG8KLS0tIGY0ZjZMUnZQd2xDYnlSWkZmdzUx
            RERDcEl3K0NRTVhlOVgvTUpXblg0WTQKUVsfgozX/WBe5UEiGyqwX55oR1GFhJal
            NGaTJ0eYL2skkWLUAdhRcvJQHZuX6qiU7/YXk0Z2M/21SHstWUpUkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:23Z"
    mac: ENC[AES256_GCM,data:lstk/EzJtzWKZ6q/QPSL6qu1LPJFuSMel4kG8Trtc+Djrx52TgMqk89V5RCKFSDAtBIHYmKgKdkfbPdlrfph2UvPXpUY0pnHTGPQ3WMj/Ae1ir9UqOnWK1KmKXrT8j95ATGWxFSn94cZpnjYju56WkD7Hy52HpCC5NpMEAKfEH4=,iv:OJ18145hnDX9mrThxxas3aCCxRtb2TLt1eBgHUFpYOc=,tag:vwKTrchbIydgh5K1xOFhnQ==,type:str]
    version: 3.13.3
