apiVersion: v1
data:
    token: ENC[AES256_GCM,data:c622Gi1UvBfZtrnHJZxA91DSchmYYKO5+crPJNoxb2gV1GiDmSno/6Ak3lAL8AiUlYTjZ260ddXWIzuocW2RpAWHcQV5xlllnUVEBarPP1YJ9fQFOPcZtA==,iv:mJxOTt0wEVcd9V7QA17Kg8i5g6jTVDA2qX+7UBnZLD8=,tag:9xuddQf7bCo9ekR4LWt+WQ==,type:str]
kind: Secret
metadata:
    name: status-heartbeat
    namespace: observability
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTXhXd2F1L0JhcXUzZm1S
            MHNvbmRBUW1sVTR3bEpvWkk0TzJaNE80UlNZCmR0bjhXMmh6T1NCQ2ZYVUc0Uzhl
            V0d4aWpTYkNJcFhkWHlkMWZEUWt4blkKLS0tIGRBaFd1TlFkUDBmOUhhWkpsQUZZ
            U1lqMFVBbFEvTEpycEIvTThDSHlISjgKejda88VmstiusaUytTPnOvOhu9DDxsq8
            WfhH+LXLRqtyUSdvOiDpVkwyGa62y7EvLK/8eUKGdAiOaC23hQrUSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UFNqY1NVN1RpTG15aXlW
            WkUva2piVFN2cXhYOC9tbFdoRXBsNzE0Y2tvCnd3QzdneXJ1MVVLSEc5QVA4SVZr
            NWVldVFxRjNTUVprWGJISFg4V0pTb2cKLS0tIFVQOG5sR0FMOXlZM0xaV0F1Yllr
            d0djRmZMUTlHU09xc1NOYldYdGozRTQK3YIAY7zA9OTbl/ziUudsqxAQEkSxzkkA
            n6hGARq1kXdVs428/gUKFOrWKyXLQ1zPMMpB+sLSgIsE+Z2bdAHlfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T21:47:58Z"
    mac: ENC[AES256_GCM,data:9pbU1/swT5fF2iZ4rAzR6M4G5clcrCczeDUeIkboHykquDZoPo0MeGISQLPfKGQN4kA593BHW/ylc80dw7oDAP5pgMcDQQcsp4SORTLGQllheMqJoEisk8sVKbReVSNtsTlrf6rTSftTspNaClI5bZSljmKA+vtAYyxHYGmQnfw=,iv:Pv/AH3AR2ASv9duEzkD0KQV5cHHk9bMp8+FogdamFmY=,tag:pVahTDq3LeoZEjJen2Xf+w==,type:str]
    version: 3.13.3
