apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:DbxIvm08BvUKcarGGfEdC46jdJgCZZaGywQsj5XYJ0vm/N0Xf/YpKcr8oMn51/5ZH8cQIrGJckXwbfLBjVrcRiDjSvs40Tl80fI8DdDyNcsAExY4mgFjjDIdD/vUEmxqaTtuWpyun0+bCioO0espub++kNjCTMvk18L4EAQShuiw0YvUtr9efA==,iv:eBmBMjTNYhgTQR8aFonQ3IkSlqjn789Xf7b6G7xqC2M=,tag:E3txrr6ZYdmAoOR4murWBw==,type:str]
kind: Secret
metadata:
    name: ghcr
    namespace: jjforge-dev
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K3h6Tit3alZIOFVCTi9t
            RWlURUJrU2FzcVZJbFc0SjVzbTJTUjNaQUdNCkVwbDlwVDRONWpqcW5iTnl3VjVF
            cWdiTElwQml3dE1EZkhETXpHcEhCQlkKLS0tIDlucW5makdsZE1EZEtlNFRtUkR4
            TzlUSDVNdHNjanQ3SVFBTmtrTkJpZXcKpOCL5EWGdEba8dOZc32uvCfSxNEZOPn6
            i6bWO5Tj0JIKLdGn+HjJeu7Zi7NOJseghwyw3waxFH72ho73u9pgbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QWZicHF4ZmFsbUNjQzI5
            V2Uxak9wWkFVc05iYk8xanBja1pqM1c2RUEwCjdxcHlpdU4rTVRiTURnOHRXMkFD
            NHYvMFN4eHNwcDRDcFRvNXRwRUltSlEKLS0tIHlHeWU5dElOS0N2ZnVCT0N2SUth
            Nmw3UnB6RHA5ZDlKb0QveVBZRHBvS0UKeGoI0AomcN5KtLv5Q652LcYHAtEBE9SR
            tLLXZZjW4FEFR2q8jSQjmz5inJasb8QV+DF5RTADzeIAYsmbga297w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:58:07Z"
    mac: ENC[AES256_GCM,data:ThUSIhpMbXr1+D5P1pXBnkYi6abE878XZYyG29k1F9i/B0dYnEYEuxU9x/hF8WhhaOdHu2bhmWs3Awm5O+LFZwJm8VqWhN3ZkBFzkstkKuTw/L7dgroO3qJDgnAXoFdG0QN1fS6lYHiWmWZEm9+kx8fpRBfjVrx3kaitnrIk2hY=,iv:9dc5LDE25IOLLW47l1XB6StlOG9SApsiK5YrgvILw74=,tag:CSlUpOjIpE3EGsKfQftR0A==,type:str]
    version: 3.13.3
