apiVersion: v1
data:
    password: ENC[AES256_GCM,data:bL+y3xcjSn95h3uSUzfQK4V3nlQEt7YhRQIaURqnFek0Iu1CJwQkdOjFUiTaHS3MeF6EzyQspW0=,iv:VE3js5IR2Qh0xxhbIRzh9WOmA+WmGX7tZ/J/4VoklXw=,tag:QpcQ6GqmMTH/Gs6SvoqegA==,type:str]
    project: ENC[AES256_GCM,data:uuvau1QP6FpwODm3xuqA6w==,iv:9lqrH1HsnPgd00/8SXmtDwvNmqJy1hHsAdlPeVRLqDk=,tag:w3o2kjUAi0I5yEh3V8R/tw==,type:str]
    type: ENC[AES256_GCM,data:ErruJQ==,iv:rmQdiwGWUbHmopK58s/cQt04Vay2W5i3vJfPNKBcRiM=,tag:OvJP6/V+X1qM2kXngc1pAw==,type:str]
    url: ENC[AES256_GCM,data:iAlz4fIvIfIgAk9Nji5AQSZ9QGwgc6mv5nuLrXci1Zve/5nkD4gwHquYaO8h1N5H3vQrrjYDoo86lM4f,iv:YS0PO2KNQ7OzTRMvpVyEordU1SBf6AmH8ZQkHee0GfQ=,tag:N+G16Pvd4TpSn7WRLDShEg==,type:str]
    username: ENC[AES256_GCM,data:7BMTnRxeVE/prZfT,iv:cXA/IXTHYfsg5G5DU91A+Kxf+Ks1Vz8MCIcooIdmUl0=,tag:AddwCTcJU9w2R4056jJbFg==,type:str]
kind: Secret
metadata:
    labels:
        argocd.argoproj.io/secret-type: repository
    name: jjforge-dev-chart
    namespace: argocd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMDE4RkE2Mk5aRFVaR2hG
            M2FGQTJvZERDUSsxVjFmeGpuM0V3cVB3bmhJCkhCVDJ2bGMyYlo2NjhjdjJpWmU5
            THN0alZCQjU3WHZyUDVkZndSWGVUUm8KLS0tIFFZTzVTZnF1TjRjcTI3WTVwNzFk
            bnRoSWZOajc2QkdkOTVCVklUZTVEbjAKjprKXK+2W28Ui6h2izky312Je68BxGID
            AlvwEeZqyk7VSYnVPSPoUl2G23Nv8E2TsKxOp41Z+7WYk5C1HCHN9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R3NBR3dGYmtDRkZOWTZx
            QThodzZsSUJnQ0toa1NvV29ZK3BPV1RDQ0FVCjd0UUUxc3cwdGJ0WEQvWS9lZjVH
            c1Vsbi9RZzVYV2o1bUNRQ01WaHpYTGsKLS0tIFNzdmNwbEhmUE91akpiV3l1ZW43
            OFIvOTVIcmFCVmlzbkF6RHlxSU8wSjAKVy4HMuFWrJSbGCckO4VqJYu66MLB84ni
            c8xyQ2xIJHob11xhgF5DUSvj8rLtaRXsYgD2zlK9cEl5jjgnDfpkbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:58:07Z"
    mac: ENC[AES256_GCM,data:JoLoW4ecixYx70xoJ66eAUG4Ti6YYYcn8DMSNE9ucgEbSpuiAZUL+1eFTpEzOCekGMGNu4bp79pTZ/tsoibB9E+dtSq6+OAbwNXXqtwXBGv4lrfqF5b19xGsgp/7/QgLrqNwDz4nsplc2hjFZYaTqoaa4LJh1WFrNhYVwd92dd0=,iv:YHb3AP/Jr3U4uU2wf/mz8pN/13aqKd5kIQKtWj+9iiE=,tag:Lm6OwYpwKyJvMO4FSvJCbQ==,type:str]
    version: 3.13.3
