apiVersion: v1
data:
    seaweedfs_s3_config: ENC[AES256_GCM,data:XSCIqs0Vit9v32XaJ/NKjz7c/RTRFrQSwyZd4MM8SH/zYuCH8h7ri1Z48ulhuuKIHjlcVjigb5L8IR4Fu0uVJLNdkZFRVPWGKT4Hm8MpgPFl36E6U2mN4ajQ0iI30BcYa0YvQrmRST+O6C+QZSDvky/nJSFIkWdvPtNUtqtWrU7X1EIvesxM8zqM9VKo44n2dR/u2MfOseo/Q0N28tNtN41BlsPTcbTQUyMC4zZcqANqsJoIZ3tezjIy8BbhrD0bb6Qi4SWsaVofGfZycwLn2e0mAtodIzocvTZqIGEMs0JI5EY0D53l6qMW2pxa5VjV2AGDQ6jnlhWriV/I616C/q9orYUJSrtdUBJCNMmmAXY=,iv:2HCxvErjTN33WOsxvuJ93czGd9Na41GISi4L3rDEfuI=,tag:UXTjakH0DmE1qxjkfonJSw==,type:str]
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: jjforge-dev
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRXdpSnZWMmk1UnpRcFNq
            dUhXR2F2dVN4REtmV3h0Z2hzUmgwNkt2L0drCkFtM1Nkb0c1Q2oxdXpqMXZKeVBV
            dmk5RzdBNFNZbkVoRFN5Y2l2NGNFRzQKLS0tIHlaOU9yRjRVTURkcjlEeE0rc293
            bXYrczM1U2E4UGplZ1NWMVo3a0dpTncK5HyvWydvwCaSYZJDofQE2dB7YhgrpOul
            KOuLeHVENL0PFnmAxmHnWWTbDd027Pk9uftTFpPlj+X3RhusUAwk/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T2RsdDBTYnlTWnIvUjBj
            Z2RLS0NpcjYybDQvRlJLMDUxM0d2V3VvVEVrClh3Sy9kclhod2Q4ZmlHcnY2dldW
            djNNdzlrM3RrTTd0UmxLWW9JbWt1T0EKLS0tIHJlS2czU21oc2Q0ZFN1Tnd1bnNM
            S3lidTcydzZQNHVQbFpZOWNwRkdCclUKdQQmeoetzkMeP7Q/P94IgubJ5qGfalre
            yir2OmGoCb3Hau3YsLUyXmJ4SvqF1ybQlDL+WNIPHG+2qzw4JcOcZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T21:36:54Z"
    mac: ENC[AES256_GCM,data:UMeAjTLaoQWuYAi7q/f6EGddQcjq5XttkUrsspIASrmEvwELyTPULWqsQwQ8kKnY7H2sQg4aKuD93HWNZC4SAN2/PUxKfRH8FV3rT6EA6fpGQA5/lz91a8lyPLbhRgpeujzOIFhNOoLSSfxKUwyx8tdW6KAM+r0QlscJ1te4Fgk=,iv:dCR035eLmTsU08xdrPhAX/n/kt8Pvwzd6fvrajPStEI=,tag:pLUv7uWalpDd8LbdygFH4g==,type:str]
    version: 3.13.3
