apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: seaweedfs-s3-config
    namespace: jjforge-dev
spec:
    secretTemplates:
        - name: seaweedfs-s3-config
          stringData:
            seaweedfs_s3_config: ENC[AES256_GCM,data:dbZAl1mN48l6b+nJnjoT4UYsLQUkyfME9LCKRt/O3uUYUhdLJIjQtYa3JQNQgGmFZ5weYIiUA07W7k80hQ3jVKoI2RA7YZLlLHhlBSO+puaAYRP9z+HojeOfngR7oP3b5p9Tj7xh1abrg4V2+e4ua8wXYcsiWVv4Jeio0hRhYjVE75Nmd10lRnTj82X0t8Dxws2W3ejBt484/nzHoj0lgN4TdxDT5/kivzFW0ViM4NgEszLJOfiK2ejbUXhAOpeDRSYzF9Ci+brY1imw,iv:+Bl1mkZP41wFq6McCgzuKrNLi7JWGqjaUlze4iiVkyk=,tag:f3u00Cc/q4TTAcfNKmwz7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOWFSdUx1Vm0yMVdKaldR
            L0R4RTN2K29JVm9JdG8yYTJJdVFDUHFBVlhjCmdMdklNL3g4QWVUa0NFU1l4Ly94
            dVp2NzZyYkNGOUVuSHQyVzROY2JWZ1UKLS0tIHlVRVpicFVTMDZFNWlYcUlpUVNF
            WXNkUmhNaW1uQjB2WlVvTDRnUUxkTEkKDXBRHuCRdj2TdZZJQXWV/ENNlVJ9onmi
            gt9bzf/B0JFV5C8kzPPJnnY6dJnZgGVHdV+VEDi98E9+b7dlvsQLnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19dktsaqcp6xdhqwtq4qygk0y5ea5uc8y20dtez4jjua2nv4r0alslxp6s5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb1IzeXVPMWNQLzU0NUUw
            bnhXdlY0WmZUMHpsSUJpcTJmdXZEZWJVOENNCktLdWFJSGtIS0I5TDNNUld5Z3Nw
            UHJQZ1B6bVZGYzQvb21CZzJuUGVkU3cKLS0tIDVURUNvTTRCSHhDVW81QlptOEhU
            TE9seDlvdDF0QkNFVTFmR0tBdzR4T2MKy/O6Tt0ma25ukfpEqaY3B/M9Ft6T9mJ6
            u4Kc51oZUbxNkVcMJKz/t+aT6IK28ut2UIxWV84iJvgcHsmG5aLd4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8xgtntlm6ynx4lf6xsaeaya8wt5cy3ur2j46k7f5njq6nqpu92s8sf7ht
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcHRvcjN5U3pLNitrZHM4
            UkV2cnZkaW1GU1BqNUxIK1pSbFkzNjFod2g0CmhRUDlCYnRHSHZCUWo0RFlNd1Yr
            cTJHZ2VFWHFoNUZnb1R6Mk4vZmNhcmcKLS0tICttaW9rT3FYQXJTa2Vva2FpMnBW
            ekJaY3ZtbHphalVyUTlaS0c1WXhXRGsKuVfASKRfYfjSiV/m14cLKLNyrmQ+s8yx
            yGghYjTfjEUG8b9sKjlymSnDKGOx+vOuTYAliwUkrMHnaqwWVkr3MA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6j54pjgnjgfw9hv6ephcsasphcv3rdwz7zr9c5980w2j395n3rqyc3z37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:06:57Z"
    mac: ENC[AES256_GCM,data:5oR426h0Mymvj25JW4zT3tc2OHqLMe9rddMcAwawEub5vzUJuQBC38z6a5/NPB+EaCRAutNhbS2k5YDzCVTHBGJ4ZNvtClkxShDbZp4k9o6AMXqXXQigi8E1MrJTe4ce+AeKE2So8XXuEFn1MTN4KTcr1jRfVXctMi6G731lLYE=,iv:+JRR+HguLzOoB/1pII3ibnR6EVXe3uaNV3v7eqQftjA=,tag:RJNpCaD9NH/NlijApXQ0EQ==,type:str]
    version: 3.13.3
